- src/ApiHandler.ts
+ Adds `tip` to extrinsics.
+ Adds `events` to extrinsics, will be empty if state has been pruned for a given block.
+ Adds `success` to extrinsics. `boolean`, or `string` with an error if state has been pruned for a given block.
> Extra data on blocks

- package.json
- src/ApiHandler.ts
Trying to fetch queryInfo on sudo extrinsics always fails, still figuring out why.
> Skip queryInfo on sudo module

- .gitignore
- package.json
- src/ApiHandler.ts
- src/main.ts
- yarn.lock
+ Fixes issues with Kusama blocks that had mismatched metadata.
> Bump to @polkadot/api 1.4.0 beta

- package.json
- src/ApiHandler.ts
- yarn.lock
> Upgrade account balances to new RPCs

- README.md
- package.json
- src/ApiHandler.ts
- src/main.ts
- yarn.lock
+ Added `/payout/` endpoints.
+ Version bump.
> /payout/ endpoint

- README.md
- package.json
- src/ApiHandler.ts
- src/main.ts
- src/utils.ts
+ Adds `/tx/artifacts` and `/tx/artifacts/NUMBER` endpoints.
> Add /tx/artifacts[/NUMBER] endpoints

- src/ApiHandler.ts
> Return on_initialize & on_finalize events from /block

- src/ApiHandler.ts
- src/main.ts
- src/utils.ts
Move function to utils and remove an `idx` that was unnecessary.
> Tiny refactor

- src/ApiHandler.ts
see https://github.com/paritytech/substrate/blob/0b274c98b2c43c505aca8a144c0138ae0266156d/frame/transaction-payment/src/lib.rs#L138-L182
> Rename variables, better comments

- src/utils.ts
Reverts paritytech/substrate-api-sidecar#93
> Revert "Gracefully handle options in `sanitizeNumber`"

- README.md
- src/config.json
- src/main.ts
- tsconfig.json
and adding custom types when connecting to remote Substrate end-point
> Adding support of reading config file 

- src/ApiHandler.ts
- src/config.json
- src/main.ts
> Fix small linting errors

- .github/workflows/pr.yml
> Setup `pr.yml` to lint

- README.md
> Fix env var name  in readme

- tsconfig.json
Additionally removes unused "include" directories.
> Update tsconfig with stricter settings

- src/config_setup.ts
- src/main.ts
- src/middleware/logger_middleware.ts
- src/types/middleware_types.ts
Better use of express types and increased consistency with "I" prefix for interfaces.
> Small type update

- src/services/blocks/BlocksService.ts
- src/types/responses/Block.ts
> Remove `newArgs` field from block response

- src/services/accounts/AccountsBalanceInfoService.spec.ts
- src/services/accounts/AccountsVestingInfoService.spec.ts
- src/services/blocks/BlockService.spec.ts
- src/services/mock/index.ts
- src/services/mock/mockApi.ts
- src/services/mock/mockBlock789629.ts
- src/services/mock/testAddress.ts
- src/services/pallets/PalletsStakingProgressService.spec.ts
- src/services/runtime/RuntimeMetadataService.spec.ts
- src/services/runtime/RuntimeMetadataService789629.json
Changes:
- Unit test `RuntimeMetadataService`
- Break out some functions from `mockApi.ts` into separate files
> Unit test `RuntimeMetadataService`

- src/controllers/transaction/TransactionMaterialController.ts
- src/services/transaction/TransactionMaterialService.spec.ts
- src/services/transaction/TransactionMaterialService.ts
- src/types/responses/TransactionMaterial.ts
> Add `noMeta` query param to `tx/artifacts`

- package.json
- src/main.ts
- yarn.lock
Bump to latest polkadot-js/api in order to get proper `Announcement` definition.
> Bump @polkadot/api

- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/report-bug.md
- .github/PULL_REQUEST_TEMPLATE/pull-request-template.md
- CONTRIBUTING.md
This PR includes:
- Two issue templates 
- One pull request template
- Contributing file
> Created GH Templates

- src/controllers/transaction/TransactionSubmitController.ts
- src/services/accounts/AccountsBalanceInfoService.ts
- src/services/accounts/AccountsStakingInfoService.ts
- src/services/accounts/AccountsStakingPayoutsService.ts
- src/services/accounts/AccountsVestingInfoService.ts
- src/services/blocks/BlocksService.ts
- src/services/node/NodeTransactionPoolService.ts
- src/services/pallets/PalletsStakingProgressService.ts
- src/services/runtime/RuntimeCodeService.ts
- src/services/runtime/RuntimeMetadataService.ts
- src/services/transaction/TransactionDryRunService.ts
- src/services/transaction/TransactionFeeEstimateService.ts
- src/services/transaction/TransactionMaterialService.ts
- src/services/transaction/TransactionSubmitService.spec.ts
- src/services/transaction/TransactionSubmitService.ts
- src/services/v0/v0accounts/AccountsBalanceInfoService.ts
- src/services/v0/v0accounts/AccountsVestingInfoService.ts
> Remove `ensureMeta` from v1 services

- src/main.ts
> Instantiate controllers in App

- CONTRIBUTING.md
- README.md
Updates the Contribute section of the README to link to CONTRIBUTING.md.
> Update Contribute section of README

- MIGRATION_GUIDE.md
Not sure if we want this in the repo - but posting here as a starting point.
> feat: Migration guide

- docker-compose.yml
> Add sample docker compose

- CHANGELOG.md
- package.json
This should be merged before any other open PRs
> chore(release): 1.0.0-rc4

- README.md
Signed-off-by: lovesh <lovesh.bond@gmail.com>
> Fix endpoint in Readme

- docs/src/openapi-v1.yaml
This fixes a minor indentation bug inside of the docs.
> docs: fix indentation

- CHANGELOG.md
- package.json
- yarn.lock
Update @polkadot/api to 3.10.2 to address https://github.com/paritytech/substrate-api-sidecar/issues/445
> chore(release): 3.0.4

- .github/workflows/publish-release-container.yml
> CI: doesn't accept commas in tags list

- CHANGELOG.md
- package.json
- yarn.lock
New release, no major changes with a low priority. 
Update 2 packages:
* @polkadot/api -> 4.1.1 [Link](https://github.com/polkadot-js/api/releases/tag/v4.1.1)
* @polkadot/apps-config  -> 0.84.1 [Link](https://github.com/polkadot-js/apps/releases/tag/v0.84.1)
> chore(release): 4.0.1

- CHANGELOG.md
- package.json
- src/services/pallets/PalletsStakingProgressService.ts
- yarn.lock
Release v4.0.2:
Updated:
`@polkadot/api => v4.2.1`
`@polkadot/apps-config => v0.85.1`
Added
`@substrate/dev` for config consolidation.
> chore(release): 4.0.2

- CHANGELOG.md
- package.json
> chore(release): 4.0.4

- src/controllers/paras/ParasController.ts
- src/services/paras/ParasService.ts
- src/types/responses/Paras.ts
- src/types/responses/index.ts
This PR adds crowdloan endpoints to the ParasController.
Specifcally:
`/crowdloans?fundInfo=boolean`
`/:paraId/crowdloans-info`
> feat: mvp crowdloan endpoints

- CHANGELOG.md
- package.json
- yarn.lock
PR for Release 4.0.5.
Updated:
`@polkadot/api`
`@polkadot/apps-config`
Fixes, edge-case regarding calculating weight in `createCalcFee`.
> chore(release): 4.0.5

- src/chains-config/dockMainnetControllers.ts
- src/chains-config/dockTestnetControllers.ts
- src/chains-config/metadata-consts/dockConsts.ts
- src/chains-config/metadata-consts/index.ts
Signed-off-by: lovesh <lovesh.bond@gmail.com>
> feat: Add weight for Dock mainnet

- CHANGELOG.md
- package.json
Release for PLO endpoints. 
I am not perfectly sure how to structure the release notes specific to this experimental release. So any and all suggestions are probably better than what I have.
NOTE: I did a double check with Rococo, and manually tested every route again as a sanity check, and everything went fine.
> chore(release): 4.0.8

- README.md
Updates the pre-requisites field in the readme for node 14.
> fix: readme docs for node version 14

- CHANGELOG.md
- package.json
- yarn.lock
> chore(release): 6.0.0

- package.json
- src/services/accounts/AccountsAssetsService.ts
- yarn.lock
Upgrade the Polkadot deps. 
Fix AssetApprovals with the most recent updates to substrate.
> fix: asset approval parameter change, update polkadot deps.

- README.md
- yarn.lock
Update the release docs to use yarn dedupe, and fix the util-crypto packaging
> fix: yarn package deduplication

- README.md
- package.json
- yarn.lock
> chore(release): 7.0.3

- README.md
- calc/Cargo.toml
- calc/pkg/package.json
Update the Docs for releasing the calc package, but also prepare the calc package for a release.
> chore(release-calc): 0.2.1

- README.md
- package.json
- scripts/README.md
- scripts/run_chain_tests.py
Just a wee tweak to the run_chain_tests script and associated docs so that we can run individual tests more easily (given that they seem to be fairly likely to fail in my case at least)
> Make it a little easier to test individual chains

- calc/Cargo.toml
- calc/pkg/package.json
Update versions to release @substrate/calc
> chore(release-calc): 0.2.2

- CHANGELOG.md
- package.json
> chore(release): 9.0.0

- package.json
Change argparse from dev dep to normal dependency to fix global package.
> fix: argparse dep

- package.json
Introduces a fix for the global package in regards to arg parse.
> chore(release): 9.1.2

- .github/workflows/publish-release-container.yml
It's fixed in https://github.com/redhat-actions/buildah-build/issues/45
> CI: remove the workaround of a buildah action bug

- helm/.helmignore
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/templates/_helpers.tpl
- helm/templates/deployment.yaml
- helm/templates/hpa.yaml
- helm/templates/ingress.yaml
- helm/templates/service.yaml
- helm/templates/serviceaccount.yaml
- helm/values.yaml
The helm chart would be used to run sidecars for Polkadot and Kusama networks.
https://github.com/paritytech/devops/issues/1047
> adding helm chart to the project

- README.md
ref #656
So now it is clear for first timers
> README link to FRAME

- CHANGELOG.md
- docs/src/openapi-v1.yaml
- package.json
- yarn.lock
Release for 9.1.11
This release fixes the npm build error that is happening for 9.1.10.
> chore(release): 9.1.11

- package.json
- yarn.lock
> fix: bump polkadot deps

- src/chains-config/metadata-consts/polkadotConsts.ts
add 9122 to the blockstore for polkadot
> fix: update blockstore for polkadot

- src/services/pallets/PalletsStakingProgressService.spec.ts
- src/services/pallets/PalletsStakingProgressService.ts
rel: [#698](https://github.com/paritytech/substrate-api-sidecar/issues/698)
This adds the historicApi to the PalletsStakingProgress service.
> fix: pallets staking progress historicApi

- package.json
- yarn.lock
Bumps:
`@polkadot/api` -> 6.8.1
`@polkadot/apps-config` -> 0.98.2-70
> fix: bump polkadot-js deps

- .gitlab-ci.yml
PR fixes `check-benchmark` (forgot to remove script extension)
> [ci] Fix check-benchmark

- package.json
- yarn.lock
Updates the following dependencies:
```
"@polkadot/api": "^9.10.2",
"@polkadot/api-contract": "^9.10.2",
```
> chore(deps): update polkadot-js deps

- package.json
- yarn.lock
Updates the following deps:
"@polkadot/api": "^9.10.4",
"@polkadot/api-contract": "^9.10.4",
> chore(deps): update polkadot-js api, and api-contracts

- guides/CONTRIBUTING.md
- Minor addition regarding `yarn lint`
- Changes in the "Ask for Help" section
> docs: Additional changes in contributing page

- e2e-tests/latest/endpoints/index.ts
- e2e-tests/latest/endpoints/kusama.ts
- e2e-tests/latest/endpoints/westend.ts
- e2e-tests/latest/index.ts
- scripts/config.ts
- scripts/e2eHelpers.ts
- scripts/runHistoricalE2eTests.ts
- scripts/runLatestE2eTests.ts
Remove `checkWsUrl`,
Add config for kusama, and westend.
rel: https://github.com/paritytech/substrate-api-sidecar/pull/1222
> tests: fix e2e tests, add kusama westend, and remove ws check

- package.json
- yarn.lock
Update the following deps:
"@polkadot/api": "^9.14.2",
"@polkadot/api-contract": "^9.14.2",
"@polkadot/util-crypto": "^10.4.2",
> chore(deps): update polkadot-js

- RELEASE.md
Making some small updates in the RELEASE guide.
> docs: update release guide

- package.json
- yarn.lock
closes: https://github.com/paritytech/substrate-api-sidecar/issues/1306
> chore(dev): switch from tsc-watch to ts-node-dev

- .gitlab-ci.yml
Addresses https://github.com/paritytech/ci_cd/issues/868
> ci: use buildah image defined in gitlab group vars

- .gitlab-ci.yml
Revert switching to linux-docker because of new k8s instance types
> revert: 0178734482a2054f1918e4d840ea32f3b6c1c049

- docs/package.json
- docs/yarn.lock
- package.json
- yarn.lock
Updates non pjs deps to new patch and minor versions.
> chore(deps): update non pjs deps in root & docs folder

- docs/src/openapi-v1.yaml
Opened a separate PR to update the docs for the `dry-run` endpoint mentioned in this [PR](https://github.com/paritytech/substrate-api-sidecar/pull/1519/files) (since they were not merged in that PR).
> docs: update docs for dry-run endpoint

- docs/package.json
- docs/yarn.lock
- package.json
- yarn.lock
Updated non polkadot-js deps in root & docs folder (minor & patch releases).
> chore(deps): update non pjs deps

- src/controllers/controllerInjection.spec.ts
Replacing unavailable Bifrost endpoint. 
All tests pass with `yarn test` now.
> fix: replace unavailable endpoint

- CHANGELOG.md
- docs/src/openapi-v1.yaml
- package.json
> chore(release): 20.6.0
