- package.json
- src/ApiHandler.ts
+ Added `info` to extrinsics in block endpoint, which contains a calculation of all tx fees.
+ Added `nonce` to accounts in balance endpoint.
> Extrinsic queryInfo, account nonce

- package.json
- src/ApiHandler.ts
- src/main.ts
- src/utils.ts
- yarn.lock
+ All big integer instances in the API should now be printed as decimal strings.
+ Updated `@polkadot.api` to 1.9.1.
> Sanitize numbers

- src/ApiHandler.ts
See: https://github.com/paritytech/substrate/issues/5943#issuecomment-628184778
I tested this and it works:
```
Actual Balance:   997999664157491
Expected Balance: 997999664157491
-------------------
Difference:                     0
```
> query info from parent

- package.json
- src/ApiHandler.ts
- yarn.lock
+ **[breaking]** `paysFee` on `system.ExtrinsicSuccess`/`system.ExtrinsicFailed` events can now be a string `"Yes"` or `"No"` on newer runtimes.
+ To provide a stable API, all extrinsics now have a `paysFee` field directly on them that is guaranteed to be `null` (if no success or failed event is present) or a boolean.
+ Fixes the transaction fee amount (#41).
+ Bumped `@polkadot/api` to `1.14.0-beta.20`.
> Handle new paysFee enum

- README.md
- src/ApiHandler.ts
- src/main.ts
Change `extrinsic` to `tx`. Although you could submit an extrinsic here, it wouldn't make much sense as only signed transactions actually pay fees. Also one would expect the same post body, `'{"tx": "0x..."}'`, as submitting the transaction.
> Rename fee variable

- package.json
- src/ApiHandler.ts
- yarn.lock
`specName` comes from an RPC call but AFAICT, nothing returns the `chainName` for the registry. Used a switch/case block here but I could see many possible approaches to this:
1. ~~Leave as is. The reason I did this is because TxWrapper's registry will only accept `'Polkadot' | 'Kusama' | 'Westend'`, so I explicitly filter for them here.~~
2. ~~Remove the switch/case and just do the `default` block now, which capitalizes the first letter of `specName`. This assumes that all chains and the Polkadot JS API type registry will follow this `specName`/`chainName` pattern.~~
3. ~~Just remove `chainName` from the return entirely and let people deal with this `specName -> chainName` conversion on the outside.~~
4. Some RPC endpoint actually does return `chainName` and this is all pointless.
To …
> Add specName and chainName to Artifacts

- README.md
closes #65
companion #50
The new instructions worked on my machine (macOS Mojave 10.14.6) so hopefully safe to assume they should work for target audience.
> Add wasm-pack install instructions to README.md

- src/main.ts
Probably should use something like typedoc, but thought I'd get started with this. We should also consider adding `/docs/` endpoints that would fetch the docs from the metadata on anything returned.
> Add doc comments to main

- calc-fee/Cargo.lock
- calc-fee/Cargo.toml
- calc-fee/src/lib.rs
- src/ApiHandler.ts
The current kusama runtime (1062) uses an older `Fixed128` implementation than polkadots runtime to calculate its fees. Unfortunately this implementation comes to a different result for the same input making the off-chain fee calculation incorrect.
This fixes this issue by using the legacy `Fixed128` implementation when kusama#1062 is detected and the current implementation otherwise.
> Fix fee calculation for kusama

- src/ApiHandler.ts
- src/main.ts
Response from Kusama looks like this (note that when I ran against local dev node the author ID was not defined)
Closes #74
> Add author ID to `/block` response

- README.md
- src/main.ts
- src/utils.ts
> Get Block Should Accept Hash

- src/ApiHandler.ts
> Fix bug when fetching genesis block

- package.json
- yarn.lock
Closes #80 
`tsc-watch` watches for changes to the codebase. Whenever a change is detected the typescript is transpiled and node runs the js artifacts.
This functionality is accessed by running `yarn dev`
> Create `dev` script with `tsc-watch` to implement live-reload

- src/utils.ts
In order to help ensure proper behavior when iterating over an array based type, it is necessary to check if it is an option first. In the case of it being an option it should be unwrapped, allowing iteration.
> Gracefully handle options in `sanitizeNumber`

- README.md
- package.json
- src/ApiHandler.ts
- src/main.ts
- Delete `payout/:address` and move that info to '/staking' in order to create a single endpoint for an accounts staking info.
- Start migration to a _more_ RESTful resource model by changing endpoint paths.
- Rudimentary error handling improvement in `get`
tl;dr - we should think about changing the path to `accounts/:address/staking/:number` because it more accurately models our resource taxonomy.
As we approach V1 and dialing in the api, the importance of communicating meaning through our endpoint increases and thus it behooves us to carefully consider how they model resources.
After offline discussion with @danforbes, consensus has begun to coalesce around modeling the resource `accounts`, representing the (collection of) `AccountId`s of the chain. Under `accounts` we would then have …
> Reconfigure `/staking/ADDRESS` to accept stash and give `controller`, `rewardDestination`

- README.md
- package.json
- src/main.ts
- yarn.lock
Closes #84 
Use `morgan` to log HTTP request/response and create the env var `LOG_MODE` which has the options "all" and "error". When set to "all", every request/response will get logged. When set to "error" only request/response that result in a status code of 400 or greater will be logged.
When not explicitly set, `LOG_MODE` defaults to "error". In order to have no logs, simply set `LOG_MODE` to anything other than "error" or "all". 
- Write logs to file in production mode
- Customization of logging messages specific to sidecar use
- Set up`dotenv` to declare ENV vars
> Logging and LOG_MODE "errors" ||  "all"

- README.md
- calc-fee/Cargo.lock
- calc-fee/Cargo.toml
- calc-fee/build.sh
- calc-fee/src/debug.rs
- calc-fee/src/lib.rs
- calc-fee/src/panic.rs
- package.json
- src/ApiHandler.ts
This PR adds support for the [upcoming](https://github.com/paritytech/polkadot/pull/1263) polkadot, kusama and westend runtimes. Westend starting with runtime 10 is now also support but untested.
In addition to these changes I also added the following modifications:
- By building the calc-fee rust project with `FEE_DEBUG=1` in the environment you get some nice debugging output
- I moved the runtime switching logic to the calc-fee project.
> Support upcoming runtimes

- calc-fee/build.sh
- src/ApiHandler.ts
The fee calculation of the first block of a new runtime did not work because its parent falsely proclaims to be produced under the new runtime. This workaround therefore uses the parent of the parent in order to determine the correct runtime under which the current block was produced.
> Fix fee calculation at runtime upgrade

- src/main.ts
Closes #67
Instead of handling this as its own validation in the middleware pipeline, I realized it makes more sense to do the validation in getHashForBlock. My reasoning is that proper validation requires a call to get the latest block. In getHashForBlock we do several less expensive checks prior and then only check for invalid height if the rpc query getBlockHash fails. Finally, some error catching is added in the get and post wrappers to check for the recently introduced HttpError.
> Give correct error for too high block number

- src/main.ts
- src/types/request_types.ts
Currently the body of post requests are just `any`. Since all posts request are for `tx` submission or estimate, we can change this any to a type that is specific to the `tx` request body format. I introduced `TxRequest` and `TxRequestBody` as types and added them to `post` and the handlers for `/tx` and `/tx/fee-estimate`
> Add `TxRequest` type

- .env-sample
- src/main.ts
- src/middleware/logger_middleware.ts
- src/types/middleware_types.ts
To create a consistent directory structure in which all middleware functions are housed within the middleware folder, the logger middleware is moved in that folder. Additionally, a middleware type is added.
> Move logger middleware to their own file

- package.json
- src/config_setup.ts
- src/main.ts
It is important to abort if the config is not valid.
This PR shows the compact version of the config if the config is ok, as info for the user.
However, if the config is NOT ok, it will show the full (= not compact) version to help the user figure out the issue then exit.
Here is a run where I am passing a bad W_URL:
```
$ NODE_ENV=web3 SAS_SUBSTRATE_WS_URL=BAD y start
yarn run v1.22.4
$ yarn run build && yarn run main
$ tsc
$ node ./build/src/main.js
SAS:
📦 EXPRESS:
✅ LOG_MODE: errors
Log level
✅ BIND_HOST: 127.0.0.1
Network interface we bind to
✅ PORT: 8080
Port of the web service
regexp: ^\d{2,6}$
📦 SUBSTRATE:
✅ NAME: Default Substrate Dev Node
Name for our node endpoint
❌ WS_URL: BAD
Websocket URL
regexp: ^wss?:\/\/.*(:\d{4,5})?$
Your config is NOT valid, exiting
error Command failed …
```
> Add config validation

- src/ApiHandler.ts
- src/types/response_types.ts
- yarn.lock
Closes #145 
In an effort to clean up all the `eslint-disable` and just generally have better typescript code, I added types for all public functions in ApiHandler. 
New code is straightforward. The main thing I want to discuss is the naming conventions this PR establishes. 
In order to prevent naming collisions with polkadot-js types, I prefixed `I` in front of all the new interfaces I introduced. Just from my last month of writing TS I have seen this pattern fairly often while perusing the inter-webs, however not sure if this is the right use. I would say this establishes the precedent that all future interfaces should be prefixed with an `I`.
I realize that many of these don't have polkadot-js name space collisions, however for the sake of consistency I feel we should either go all or …
> Add explicit return types for public functions in ApiHandler

- .dockerignore
- .env.local
- Dockerfile
- README.md
- package.json
- specs.yml
- src/config_setup.ts
- src/main.ts
This PR adds docker support:
- `yarn build:docker` will build the image (you need `jq` installed)
- I added code to handle SIGINT (= CTRL+C), which is especially important while running in a container
- I fixed the default config so "it works ™" right away without any config/profile or local node(nice for demos...)
- I added a default local profile to easily switch to a local node (`NODE_ENV=local yarn start`)
Once the image has been built, you may test it with:
```
export VERSION=`cat package.json | jq -r .version`
docker run --rm -it -p 8080:8080 substrate-api-sidecar:$VERSION
```
You may also test without building anything with:
```
docker run --rm -it -p 8080:8080 chevdor/substrate-api-sidecar
curl -s http://127.0.0.1:8080/block | jq
```
> Dockerfile

- src/main.ts
- yarn.lock
> Add chainName to server connecting message

- package.json
- src/utils/test_util.ts
- src/utils/utils.spec.ts
- src/utils/utils.ts
- Add support for 
- Codec HashMap
- BN
- native js Map (alot of Codec is derivative of Map so I think this is good to support)
- DRY, reorganize test code with constants for commonly used numbers. No tests are removed, but some are moved for better organization.
- Add test coverage 
- Add future todos for areas of polkadot-js types that still need more coverage
- Document (with testing) native javascript types that are not supported
> Add `sanitizeNumber` support for HashMap, js native Map, and BN.

- .env-sample
- README.md
- specs.yml
- src/config_setup.ts
- src/main.ts
This PR removes the NAME env var because there is not a clear use for it now that we display the type of client and the chain name. Additionally it removes the `console.log` in `main` starting with `Connecting...`.
> Remove NAME env var

- specs.yml
- src/Config.ts
Fix #165
This PR is aimed at helping the users with configuration.
Failing the config (you may trigger that with `SAS_SUBSTRATE_WS_URL=BAD yarn start` for instance) will show the following:
```
SAS:
📦 EXPRESS:
✅ LOG_MODE: "errors"
Log level
✅ BIND_HOST: "127.0.0.1"
Network interface we bind to
✅ PORT: 8080
Port of the web service
regexp: ^\d{2,6}$
📦 SUBSTRATE:
✅ NAME: "Default Substrate Dev Node"
Name for our node endpoint
❌ WS_URL: "BAD"
Websocket URL
regexp: ^wss?:\/\/.*(:\d{4,5})?$
Invalid config, we expect something like:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SAS_EXPRESS_LOG_MODE="errors"
SAS_EXPRESS_BIND_HOST="127.0.0.1"
SAS_EXPRESS_PORT=8080
SAS_SUBSTRATE_NAME="Default Substrate Dev Node"
SAS_SUBSTRATE_WS_URL="ws://127.0.0.1:9944" …
```
> Build a default config

- README.md
This PR adds relative to links to controllers from path descriptions. This will help README.md users navigate to the detailed docs in the controllers.
Follow up PRs:
- Implement Swagger UI once all v1 routes are ready
> Add links to controllers for path description in README.md

- src/main.ts
- src/services/accounts/AccountsStakingInfoService.ts
- src/services/pallets/PalletsStakingProgressService.ts
There are some unnecessary `await`s. This PR removes them.
> Remove useless `await`s in `Promise.all`s

- src/services/blocks/BlocksService.ts
Small optimization that improves response times to `/block/NUMBER` by ~100 - 200ms
> Optimize `fetchBlock` call to getHeader by parallelize-ing

- openapi/openapi-proposal.yaml
- src/controllers/transaction/TransactionDryRunController.ts
- src/controllers/transaction/index.ts
- src/main.ts
- src/services/transaction/TransactionDryRunService.ts
- src/services/transaction/index.ts
- src/types/responses/TransactionDryRun.ts
- src/types/responses/index.ts
#227 
Relates to https://github.com/paritytech/substrate/pull/6300
This PR implements `transaction/dry-run` and codifies the sidecar API.
N.B. system_dryRun will not have any effects on chain state.
---
Below are some sample responses:
```
{
"at": {
"hash": "0xd46b3789ddd9d930da20fdf7a47a6fbc41e5851b325738b378351d67e65ecc4d",
"height": "63"
},
"dryRunResult": {
"resultType": "DispatchOutcome",
"result": {
"Error": {
"Module": {
"index": "6", // balances
"error": "3" // InsufficientBalance
}
}
}
}
}
{
"at": {
"hash": "0x1de484ce19478a86d649f60c6fd79d0f2ce361555fc3706cf2cdcce38c358ebc",
"height": "32"
},
"dryRunResult": {
"resultType": "DispatchOutcome",
"result": {
"Ok": []
}
}
}
{
"at": {
"hash": "0xfa9aa674faacc41b0246a84bb908e8b53054dc2840ba7f6b87bcbf57e9988d5f",
"height": "507"
}, …
```
> Implement `transaction/dry-run`

- src/services/runtime/RuntimeSpecService.ts
- src/services/test-helpers/responses/runtime/spec.json
- src/types/responses/RuntimeSpec.ts
Closes #243 
The `runtime/spec` lets the user query for runtime version info at a specific block. As such, it should return information about the block the query was made at. Additionally, the `openapi-proposal.yaml` actually specifies the response have the `at` field.
>  Add `at` field to `runtime/spec`

- package.json
- src/controllers/node/NodeTransactionPoolController.ts
- src/main.ts
- src/services/accounts/AccountsStakingPayoutsService.ts
- src/services/blocks/BlocksService.spec.ts
- src/services/blocks/BlocksService.ts
- src/services/node/NodeTransactionPoolService.spec.ts
- src/services/node/NodeTransactionPoolService.ts
- src/services/runtime/RuntimeCodeService.ts
- src/services/runtime/RuntimeMetadataService.ts
- src/services/test-helpers/responses/blocks/blocks789629.json
- src/services/transaction/TransactionDryRunService.ts
- src/services/v0/v0accounts/AccountsBalanceInfoService.ts
- src/services/v0/v0accounts/AccountsStakingInfoService.ts
- src/services/v0/v0accounts/AccountsVestingInfoService.ts
- src/services/v0/v0blocks/BlocksService.ts
- src/services/v0/v0claims/ClaimsService.ts
- src/services/v0/v0metadata/RuntimeMetadataService.ts
- src/services/v0/v0pallets/PalletsStakingProgressService.ts
- src/services/v0/v0transaction/TransactionFeeEstimateService.ts
- src/services/v0/v0transaction/TransactionMaterialService.ts
- src/services/v0/v0transaction/TransactionSubmitService.ts
- src/types/responses/Dispatchable.ts
- src/types/responses/Extrinsic.ts
- src/types/responses/SanitizedCall.ts
- src/types/responses/SanitizedEvent.ts
- src/types/responses/index.ts
- yarn.lock
Types: https://github.com/polkadot-js/api/pull/2550
Other changes:
- deprecate `ensureMeta` entirely because `@polkadot/api` now updates registry with metadata automatically Relates to: https://github.com/polkadot-js/api/pull/2545, https://github.com/polkadot-js/api/pull/2534, https://github.com/polkadot-js/api/pull/2535, https://github.com/polkadot-js/api/pull/2543/files, https://github.com/polkadot-js/api/pull/2539
- Update extrinsic and section method in beta `/blocks`
> Deprecate `ensureMeta`; Update `method` in beta `/blocks`; Bump deps

- src/controllers/AbstractController.ts
- src/controllers/v0/v0blocks/BlocksController.ts
- src/services/v0/v0blocks/BlocksService.ts
Example usage:
`localhost:8080/block/3861985?noAuthor=true`
This will eliminate a query to `api.query.session.validators.at(hash)` and thus eliminate some network traffic.
> Allow opt out of `authorId` field in `/block` response

- docs/src/openapi-v1.yaml
- src/controllers/blocks/BlocksController.ts
> Implement `finalized` query param for `blocks/head`

- src/services/blocks/BlocksService.spec.ts
- src/services/blocks/BlocksService.ts
- src/services/test-helpers/responses/blocks/blocks789629.json
- src/types/responses/Extrinsic.ts
Closes #215 
This PR affects anything in the extrinsics array of the `/blocks` endpoint that does not have a signature.
I make the assumption that anything that does not have a signature:
- does not pay fees (`paysFee` is always `false`)
- does not have a tip (`tip` field is emitted)
- does not have a nonce (`nonce` field is emitted)
As far as I know though there is not a concrete way to distinguish between an unsigned transaction and an inherent - their external interface is the same and the differences come from how they are processed.
> Remove irrelevant fields for unsigned extrinsics

- docs/src/openapi-v1.yaml
- src/controllers/blocks/BlocksController.ts
- src/services/blocks/BlocksService.spec.ts
- src/services/blocks/BlocksService.ts
Closes #288
This PR introduces the ~`noAuthor`~ `authorId` query param to the `/blocks` endpoint. 
For some users the `authorId` field may not be necessary, and since it requires a rather slow RPC query to the validators storage item in the sessions pallet, I believe it makes sense to give the option to opt out of it.
---
Below shows the difference in response times I got when using `noAuthor=true`
```
📦 SUBSTRATE:
✅ WS_URL: "wss://rpc.polkadot.io"
2020-09-18 14:17:23 info: Connected to chain Polkadot on the parity-polkadot client at wss://rpc.polkadot.io
2020-09-18 14:17:23 info: Listening on http://127.0.0.1:8080/
2020-09-18 14:17:25 http: GET /blocks/1603921 200 1408ms
2020-09-18 14:17:31 http: GET /blocks/1603921 200 2009ms
2020-09-18 14:17:35 http: GET /blocks/1603921 200 1346ms …
```
> feat: Add `authorId` query param to `/blocks` endpoint

- CONTRIBUTING.md
- docs/src/openapi-v1.yaml
- package.json
- src/controllers/blocks/BlocksController.ts
- src/services/blocks/BlocksService.spec.ts
- src/services/blocks/BlocksService.ts
Removes the authorId query param - it did not makes its way into any release so it is non api breaking. Also bumps the version in package.json to v1.0.0-rc1 in prep for release.
> feat: Remove authorId query param; Bump version in package

- src/services/pallets/PalletsStorageItemService.ts
Previously in `PalletStorageItemService.findPalletMeta`, we checked if the found index was a falsey value (`!palledIdx`), however this check will throw on 0 since it is a falsey value in JS; meaning the user would get an error when trying to retrieve the first pallet. This PR introduces a fix by explicitly checking for undefined or an invalid number.
> fix: Find pallets with index 0

- src/main.ts
When a user is using a public known url, it is important for them to know they are accessing a public domain, and contributing to the traffic. If they are not using it for testing/development that it is advised to switch nodes. Currently there was no information added to the logger. In addition, when a user is accessing a url that is prefixed with `ws` and is not running on either `0.0.0.0`, `127.0.0.1`, or `localhost` there is no warning that states they are on an unsecure connection. 
In this PR, we are notifying the end user that they are using a public url. If they are not on a public known url it wont say anything. Also, we are adding a warning to the logger that warns the user they are on an unencrypted/unsecure connection if they fulfill the conditions stated above in the issue. …
> feat: Add Public URL notice

- README.md
Update the README to reflect that v1 has already been released.
> chore(docs): Update README v1 transition note

- CHANGELOG.md
- package.json
- src/sanitize/sanitizeNumbers.spec.ts
- src/sanitize/sanitizeNumbers.ts
- src/services/test-helpers/mock/mockApi.ts
- src/services/test-helpers/responses/runtime/metadata789629.json
- src/test-helpers/metadata/decorated.ts
- src/test-helpers/metadata/metadata.ts
- src/test-helpers/registries/kusamaRegistry.ts
- yarn.lock
BREAKING CHANGE: as documented in the diff here: https://github.com/paritytech/substrate-api-sidecar/compare/zeke-bump-multi?expand=1#diff-78b11c394fc7a8f9c96da1c99dff8d40d78af87d7b40102165467fa34b95977e the response for `runtime/metadata` has at least a known regression for polkadot runtime v16, and likely most older runtimes. I think it relates to https://github.com/polkadot-js/api/pull/2800, although not certain. The change affects the types that show up in the metadata.
Other changes:
- `Decorated` no longer exists and is replaced with the equivalent `expandMetadata` for test utilities
-  Update usage of `Int` in tests to reflect function signature change
- Factor out `Metadata` creation for test utilities
> feat!: Bump polkadot-js and document runtime/metadata API regression

- Dockerfile
ref #318
I ran into issue building the image in the previous state due to failures installing wasm-pack.
This PR allows to build the image and takes the chance to use a newer base image.
> Upgrade the base image to prevent issues while installing wasm-pack

- .npmignore
- README.md
- package.json
closes #336 
This PR focuses on two changes that should make things smoother for end users
- By adding a `.npmignore`, we remove all the TS files from the npm package and thus reduce the packages size - making it quicker to download and reducing the footprint.
- With the `start` script in the `package.json`, we used to always build the JS target files every time the service was started. While this may ease careless mistakes in development, it makes no sense for end users as the npm package ships with the already built JS and those using github only need to build once per release. This significantly reduces the start up time of the service and may be particularly helpful for those who regularly restart the service with something like cron job
> build: Trim npm package with `.npmignore` & remove build stage from start script

- docs/src/openapi-v1.yaml
- src/controllers/blocks/BlocksController.ts
- src/services/blocks/BlocksService.ts
Currently we decode `OpaqueCall`s in order to give more meaningful responses.
Recently, we ran into a scenario where the `OpaqueCall` argument simply appears to be invalid (see #343, https://github.com/polkadot-js/api/issues/2858). In this case the decoding will always fail. 
In the current release the whole endpoint will fail when the `OpaqueCall` is bad. This PR introduces a `catch` for the throw, and will now respond with the raw, hex encoded scale when the decoding fails.
> fix: Catch errors decoding opaque calls

- src/types/config/SidecarConfig.ts
If a pallet is updating a block with type Object (Record<string, string>),
there is currently no way to provide a structure/Object interface type.
Enhancing the type of the CUSTOM_TYPES to take json object with
`Record<string, string>` type would fix the issues.
Signed-off-by: Amar Tumballi <amar@dhiway.com>
> config: Enhance CUSTOM_TYPES to take Object too.

- src/services/accounts/AccountsBalanceInfoService.ts
- src/services/accounts/AccountsVestingInfoService.ts
Closes #346 
Also uses `.unwrap()` on the `Compact` block number, which should be more idiomatic then using `.toNumber()`.
> fix: Use http BadRequest (400) when balance-info not found

- .env.docker
Small typo i noticed that is misleading in .env.docker.
Just wanted to make a first PR for presenting myself before submitting new PRs 😄
> typo(env): SAS_EXPRESS_BIND_PORT -> SAS_EXPRESS_PORT in .env.docker

- package.json
- yarn.lock
We just published a new minor for `@substrate/calc`. This updates Sidecar to use that.
> chore(deps): Bump @substrate/calc dep

- package.json
closes #389 
The other option is we can just add a note in the README.md pointing people to use `node --stack_size=1300` if they want to decode blocks that contains elections solutions.
lmk if you have thoughts @dvdplm
> fix: Increase node.js stack size in order to decode election solutioins

- package.json
- src/services/blocks/BlocksService.spec.ts
- src/services/blocks/BlocksService.ts
- yarn.lock
Closes #384 
In https://github.com/paritytech/substrate-api-sidecar/pull/351, I removed the querys `api.query.session.validators` & `api.rpc.getBlock`. Additionally I removed `BlocksService. extractAuthor`. I replaced all of them with `api.derive.chain.getBlock`, which neatly gave us the `authorId` in addition to the `block`. (Opposed to having to use the validators and digest logs to extract the authorId)
However, for some reason none of the `Codec` objects returned from the derive call have a type registry dated to the call, instead they have what seems to be the most recent type registry. The effect of this is that when we try to create `Call`s that are not in the most recent metadata we get a call not found error. To solver this issue I have brought back the aforementioned code that I …
> fix: Use correct registry when creating calls; Remove usage of derive.chain.getBlock

- package.json
- yarn.lock
Closes #392 
Reverts #390
**N.B.** this has build issues due to `tsc` complaining of conflicting types. I _think_ this is because we are using a beta of polkadot-js/api and that makes lining up the versioning of packages harder. Once polkadot-js/api has its non-beta release monday we should be able to just update this branch, double check it on the polkadot `/blocks/3337808`.
> fix: Revert stack limit increase and use updated polkadot-js/api instead

- .env.docker
- .github/workflows/publish-release-container.yml
- Dockerfile
- README.md
- docker-compose.yml
- optimized Dockerfile; 
- labelled Dockerfile; 
- Github Action to build container; 
- edit docker-compose
Closes: paritytech/ci_cd/issues/51
Closes: paritytech/substrate-api-sidecar#333
> ci: build container on release

- package.json
- src/controllers/accounts/AccountsBalanceInfoController.ts
- src/services/accounts/AccountsBalanceInfoService.spec.ts
- src/services/accounts/AccountsBalanceInfoService.ts
- src/services/test-helpers/mock/index.ts
- src/services/test-helpers/responses/runtime/spec.json
- yarn.lock
BREAKING CHANGE
- Document regression (breaking change) in `runtime/spec` response. `tokenSymbol` and `tokenDecimals` now return an `Arrary<string>` instead of a `string`. See the diff for `src/services/test-helpers/responses/runtime/spec.json` to view a concrete example of the change.
- Bumps dependencies, including polkadot-js
- Accounts for updates to `chainProperties.chainTokens`. Formerly, `chainProperties.chainToken` was just a `string`; now it is a `Array<string>`, so it can be extensible for chains that support multiple tokens. In this PR we make the assumption that the token at index 0 will be the native token. We consider a token native because its balance is stored in `system::Accounts`; opposed to a non-native token which has its balance accessible via the ORML `tokens` …
> fix!: Update polkadot-js/api and account for chainProperties updates

- package.json
- src/main.ts
- src/sanitize/sanitizeNumbers.spec.ts
- yarn.lock
Changes:
- bumps @polkadot/apps-config && @polkadot/api to latest stable releases which includes some type updates for chains in polkadot/apps and type updates for test parachains
- Adjusts tests to use updated error enum type in polkadot-js (https://github.com/polkadot-js/api/commit/15ba6f62617f142ac27f48152ec539fa9bd9f244)
- Adjust types passed into `ApiPromise` from from `polkadot/apps-config` to no longer use `typesSpec` because `apps-config` no longer exports it. What was previously `typesSpec` is now included in `typesBundle` (https://github.com/polkadot-js/apps/pull/4646).
> fix(types): Update @polkadot/{apps-config, api} to get latest type definitions

- docs/src/openapi-v1.yaml
Change "height" to "number" for the docs in reference to these routes:
`/blocks/{blockId}`
`/blocks/head`
Resolves [#457](https://github.com/paritytech/substrate-api-sidecar/issues/457)
> docs: update docs for /blocks/head and /blocks/{blockId}. 

- .github/workflows/publish-release-container.yml
Fix the issue when one wants two tags has to build the image twice.
> CI: optimize buildah build x2

- babel.config.js
- jest.config.js
- package.json
- src/sanitize/sanitizeNumbers.spec.ts
- src/sanitize/sanitizeNumbers.ts
- src/services/accounts/AccountsStakingInfoService.ts
- src/services/test-helpers/responses/accounts/stakingInfo789629.json
- src/services/test-helpers/responses/blocks/blocks789629.json
- src/services/test-helpers/responses/node/network.json
- src/services/test-helpers/responses/pallets/fetchStorage789629.json
- src/services/test-helpers/responses/pallets/fetchStorageItemMeta789629.json
- src/services/test-helpers/responses/pallets/stakingProgress789629.json
- src/services/test-helpers/responses/runtime/metadata789629.json
- src/services/test-helpers/responses/runtime/spec.json
- src/test-helpers/metadata/polkadotMetadataV16.json
- yarn.lock
Enums in responses serialize with [camelCase variants](https://github.com/polkadot-js/api/pull/3024). Check spec diffs for details
- Reverses regressions in decoding blocks with [sudo proxy variants](https://github.com/polkadot-js/api/pull/3286)
- Update Jest setup to handle `@polkadot` packages that now use ESM
- Add babel config that converts JS files from CommonJS (CJS) to ECMASCript Modules (ESM).
- Update Jest config to pipe all `.js` into babel and `.ts` into tsc and specify that `@polkadot` packages should be explicitly transformed (normally node_modules are ignored). Since `@polkadot` packages ship with `.js` files, they go through the bable transpiler and spit out the CJS that Jest expects.
- Bump deps
> feat(types)!: camelCase enum serialization; Bump polkadot/api@v4 w. ESM

- src/main.ts
This PR simply adds a log message of the version of api-sidecar prior to creating the `ApiPromise` and starting up the websocket connection.
If the `ApiPromise` fails to connect (due to type issues, node not running etc.) the logging prompts following will never show up. Thus, logging the version prior to the most common failure point for new users is prudent for helping debug ([example](https://github.com/paritytech/substrate-api-sidecar/issues/479#issuecomment-802928219)).
Below is an example of the startup logging when the api fails to connect because there is no websocket port at the specified address.
> feat: Log version before creating ws connection

- docs/src/openapi-v1.yaml
- src/services/pallets/PalletsStakingProgressService.ts
- src/types/responses/PalletStakingProgress.ts
This PR resolves issue [#468](https://github.com/paritytech/substrate-api-sidecar/issues/468).
Updated `eraElectionStatus` to work for parachains, but also to work with the upcoming runtime upgrade. 
With the upcoming runtime Upgrade v30, `eraElectionStatus` will no longer be supported and therefore deprecated.
> fix: update eraElectionStatus for runtime upgrade v30

- CHANGELOG.md
- package.json
- yarn.lock
Release for v4.0.3
Packages added:
`@polkadot/api 4.2.1 => 4.3.1`
`@polkadot/apps-config 0.85.1 => 0.86.1`
`y18n 4.0.0 => 4.0.1 /docs`
Updated `PalletsStakingProgressService` to work with the upcoming upgrade regarding election's with runtime v30.
Optimize `/blocks` to fix a regression regarding expandingMetadata.
> chore(release): 4.0.3

- src/services/blocks/BlocksService.ts
This PR adds a single defensive check to `createCalcFee` in order to make sure we are not mapping over undefined `weightToFee`.
> fix(BlocksService): check all materials prior to creating calcFrom.from_params

- src/controllers/paras/ParasController.ts
- src/services/paras/ParasService.ts
- src/types/responses/Paras.ts
- src/types/responses/index.ts
- src/types/util/Option.ts
Adds endpoints:
- `paras/`: list of all registered parachains and their lifecycle stage.
- `/:paraId/lease-info`: current and future lease information for a para.
- `/:paraId/crowdloan-info`: info on a para's current crowdloan.
- `/leases/current`: list of all lease holders for the current lease period and general information about the current lease period.
- `/auctions/current`: information on the current auction.
Future PRs:
- Test for endpoints
- Docs
- Maybe merge `crowdloan-info` & `lease-info` into a single endpoint that just has all the plo info that is specific to a chain.
> Add endpoints

- .github/workflows/publish-release-container.yml
Can be reverted after https://github.com/redhat-actions/buildah-build/issues/45 is resolved.
Closes: https://github.com/paritytech/ci_cd/issues/120
> 3x8 workaround buildah gha bug

- src/services/paras/ParasService.ts
- src/types/responses/Paras.ts
changes
- correct type annotations on some queries
- use 0 as the offset for when we are not in the ending phase of an auction
- hardcode a fallback for `this.api.consts.auctions.sampleLength` because it is not yet in the metadata
- data in `winning` array is now structured with properties describing each tuple member. We also add in the `leaseSet`, which is the lease periods the bid is for
>  feat: include lease set for each winning bid in auctions/current

- docs/src/openapi-v1.yaml
- src/services/paras/ParasService.ts
- src/types/responses/Paras.ts
adds docs for
- `/paras`
- `/paras/leases/current`
- `/paras/auctions/current`
- `/paras/crowdloans`
- `/paras/{paraId}/crowdloan-info`
- `/paras/{paraId}/lease-info`
changes 
- Auction phases are now modeled as `AuctionPhase::Starting` instead of (`AuctionPhase::PreEnding`) and `AuctionPhase::Ending`. 
future prs
- tests
> docs: /paras{/leases/current, /auctions/current}

- CHANGELOG.md
- package.json
- yarn.lock
Release 4.0.6.
* `@polkadot/api` v4.4.1 => v4.5.1
* `@polkadot/apps-config` v0.86.2 => v0.87.1
* `@polkadot/util-crypto` v6.0.5 => v6.1.1
Note: There was a duplicate dependency issue with util-crypto. 
The order to download them with the lease amount of issues was api => apps-config => util-crypto. But still came with duplicate dependencies. So I deleted the yarn.lock, node_modules, and did `yarn` again, which solved the issue.
> chore(release): 4.0.6

- package.json
- src/services/paras/ParasService.ts
- src/types/responses/Paras.ts
- yarn.lock
Changes:
- Dynamically `leasePeriodsPerSlot`, but use a fallback to ensure compatibility w/ current `rococo-v1` branch which does not expose the constant in metadata (https://github.com/paritytech/polkadot/pull/2862)
- Use exact int type annotations for relevant queries instead of `AbstractInt`
> fix: Query lease periods per slot; use exact int types

- src/services/test-helpers/mock/mockApi.ts
- src/test-helpers/typeFactory.ts
* Allow `TypeFactory.storageKey` to dynamically create storage keys for any `StorageEntryBase`.
* Change `createApiWithAugmentations` dynamically create api's for testing.
* Cleanup mockApi to have clearer naming for each set of paraId constants. Also specify where rococo is being used as an api and registry typefactory
> fix: refactor typeFactory, cleanup mockApi

- CHANGELOG.md
- package.json
- yarn.lock
Updated
`@polkadot/api` v4.5.1 => v4.6.2
`@polkadot/apps-config` v0.87.1 => 0.88.1
`@polkadot/util-crypto` v6.1.1 => v6.2.1
`@substrate/dev` v0.3.0 => v0.4.1
Same as last release in order to avoid the duplicated deps, I deleted the `node-modules` and `yarn.lock` and did a `yarn` to resolve. The reason my yarn doesnt automatically dedupe is a local issue with my yarn versioning that needs to be resolved. Instead of complicating things for the release I instead did it the manual way. For next release my yarn should be resolved though.
> chore(release): 4.0.7

- README.md
This PR aims to update the documentation around releasing a new release of sidecar.
closes: [#527](https://github.com/paritytech/substrate-api-sidecar/issues/527)
> docs: update release and publishing

- package.json
- src/services/blocks/BlocksService.spec.ts
- src/services/blocks/BlocksService.ts
- src/services/test-helpers/responses/blocks/blocks789629.json
- yarn.lock
~~need to hold off on merging until I figure out how to get a valid type registry. The one of the derive block is not working~~ Using the registry from `Vec<EventRecord>` now, which seems to work.
- Bump polkadot-js/api => 4.9.2
- Document changes to serialization of `ConsensusEngineId` (see specs)
- Use `derive.chain.getBlock` to get both authorId and block. We remove the query to `session.validators` and the `authorId` extraction function because it looks like something about the new `ConsensusEngineId` serialization broke that.
We should also check to see if there is any significant performance regression from the new derive.
> fix: Bump polkadot-js/api to get parachain types: Document user contract regressions

- CHANGELOG.md
- package.json
- src/chains-config/index.ts
- src/chains-config/kiltControllers.ts
- src/main.ts
- src/services/blocks/BlocksService.spec.ts
- src/services/blocks/BlocksService.ts
- src/services/test-helpers/responses/blocks/blocks789629.json
- yarn.lock
Adding KILT to the collection of controllers.
> feat: KILT controller integration

- CHANGELOG.md
- package.json
Release PR for 6.1.0.
Tested against Polkadot, Kusama, and Westend.
> chore(release): 6.1.0

- docs/src/openapi-v1.yaml
- package.json
- src/services/paras/ParasService.spec.ts
- src/services/paras/ParasService.ts
- src/services/test-helpers/mock/mockApi.ts
- yarn.lock
Before publishing the next release this PR updates the fields `firstSlot` and `lastSlot` within type `FundInfo` to correctly match the type generated from `@polkadot/api`.
I updated the docs, tests, and service, as well as updated the dependencies.
> fix!: fundInfo with updated polkadot/api

- package.json
- src/sanitize/mockData.ts
- src/sanitize/sanitizeNumbers.spec.ts
- src/test-helpers/constants.ts
- yarn.lock
This PR updates the deps for polkadot-js, and substrate/dev
I also reconfigured tests in order to reflect the most recent internal changes to polkadot-js [here](https://github.com/polkadot-js/api/commit/400e14d6c94613e3b013f207607e4c16c61d9b4b#diff-4057209e51321417a7ba8384eeaa7221603262b495ae1f975753c129de848f4eR24)
> fix: update deps, reconfigure tests to reflect most recent polkadot-js changes

- e2e-tests/endpoints/kusama/9253.json
- e2e-tests/endpoints/kusama/index.ts
- src/services/blocks/BlocksService.ts
[BUG] Urgent
Using Kusama as an example querying any block with a runtime less than 1062 (the minimum runtime version used to calc fees for kusama) will throw an error because `api.query.transactionPayment?.nextFeeMultiplier?.at` `Multiplier` type isnt supported.  
Currently there is no check before `api.query.transactionPayment?.nextFeeMultiplier?.at` to make sure we don't calculate any fees for runtime's less than the least known runtime for fee's.
This PR fixes that by adding a check.
> fix: createCalcFee bug

- CHANGELOG.md
- package.json
- yarn.lock
closes: [#590](https://github.com/paritytech/substrate-api-sidecar/issues/590)
Update polkadot-js/api to 4.16.2 to fix for decoding of `electionProviderMultiPhase`.
> chore(release): 7.0.5

- e2e-tests/endpoints/kusama/7673144.json
- e2e-tests/endpoints/kusama/7944249.json
- e2e-tests/endpoints/kusama/8049096.json
- e2e-tests/endpoints/kusama/8113510.json
- e2e-tests/endpoints/kusama/index.ts
- e2e-tests/endpoints/polkadot/5705186.json
- e2e-tests/endpoints/polkadot/index.ts
- src/chains-config/metadata-consts/kusamaConsts.ts
- src/chains-config/metadata-consts/polkadotConsts.ts
- src/chains-config/metadata-consts/westendConsts.ts
Updates sidecar's cache for runtime versions used to calc fees.
Updates the e2e tests for kusama and polkadot for the most up to date runtimes.
> chore: update the runtime versions used in the blockstore, and e2e tests

- docs/src/openapi-v1.yaml
- src/services/paras/ParasService.spec.ts
- src/services/paras/ParasService.ts
- src/services/test-helpers/mock/mockApi.ts
- src/services/test-helpers/mock/mockBlock789629.ts
- src/types/responses/Paras.ts
closes: [#588](https://github.com/paritytech/substrate-api-sidecar/issues/588)
This PR aims to reflect the addition of the `AuctionStatus` enum in polkadot for parachains, specifically the `VRFDelay`. When an auction is past its `finishEnd` block the auction is then in a `vrfDelay` phase. 
* I updated the tests to reflect this change, I also spotted a minor issue in the tests and reversed the output results to reflect a real world scenario with the auctions.
* Added logic inside of the `auctionsCurrent` method for `ParasService` that will add a `vrfDelay` phase as a potential result.
* I added the `vrfDelay` result to the `AuctionPhase` type, and changed `starting`=> `startPeriod`, `ending` => `endPeriod`. 
Overall there are 3 potential return values for a phase:
```
phase :
startPeriod …
```
> fix: add `vrfDelay` as a `phase` return value for ongoing auctions to reflect VRFdelays in polkadot

- CHANGELOG.md
- package.json
- yarn.lock
Weekly Sidecar release v8.0.1.
Updates the chain specific types via polkadot-js.
> chore(release): 8.0.1

- CHANGELOG.md
- package.json
- yarn.lock
Update @polkadot/apps-config for the latest chain specific types. The main concern about this release is that it updates a peer dependency inside of polkadot-js called `@darwinia/types` out of an alpha version and into stable release.
> chore(release): 8.0.2

- README.md
- package.json
- src/test-helpers/registries/kusamaRegistry.ts
- yarn.lock
This updates apps-config adds @polkadot/x-rxjs, and the resolutions in package.json.
> fix: update deps, resolutions

- CHANGELOG.md
- package.json
- yarn.lock
* feat: add /blocks/:number/header, and /blocks/head/header ([615](https://github.com/paritytech/substrate-api-sidecar/pull/615)) ([b7c2818](https://github.com/paritytech/substrate-api-sidecar/commit/b7c2818c57718526265f8104d9979a3cca127e3e))
* feat: Basic support for H160 and H256 accounts. ([596](https://github.com/paritytech/substrate-api-sidecar/pull/596)) ([bddc2a2](https://github.com/paritytech/substrate-api-sidecar/commit/bddc2a28c0477126a5aea4418188dedbf483e6d6))
* Update @polkadot/api to get the latest substrate specific upgrades.
* fix: rewrite sidecar e2e script ([618](https://github.com/paritytech/substrate-api-sidecar/pull/618)) ([423574e](https://github.com/paritytech/substrate-api-sidecar/commit/423574e5db9828be6bb3f7721302829b1cd0661c))
> chore(release): 9.1.0

- docs/src/openapi-v1.yaml
Update the schema of the swagger ui docs to be in alphabetical order. Unfortunately the schema portion doesnt have built in alphabetical order support, and a plugin is needed in order to facilitate that, therefore I just switched it all over manually. I think manually switching it over is nice anyways, it will make it easier to organize when updating the docs if need be.
> docs: alphabetical order for schema types

- docs/src/openapi-v1.yaml
closes: [#624]
I updated the docs to reflect the actual return value of ChainType via polkadot-js. 
The route this is associated with is `/runtime/spec`.
The enum ChainType has 4 variants:
```
- Live => null
- Development => null
- Local => null
- Custom => string
```
The old docs reflected that the return value is a string, but instead an object is returned with the key as one of the variants, and the value as null except when the variant custom is used, in which case a string will be the value.
> docs(ChainType): fix docs for chaintype return value

- src/controllers/blocks/BlocksController.ts
This fixes the default behavior for querying the finalized head. The query param and its expected behavior still works. The only issue is the `/blocks/head` endpoint is not returning the finalized head by default, which means you have to tag the finalized param onto the query. This fixes the slight bug introduced in this PR [#615](https://github.com/paritytech/substrate-api-sidecar/pull/615).
> fix: finalization for `/blocks/head`

- CHANGELOG.md
- package.json
- yarn.lock
Update @substrate/dev dep, 
Update the changelog from an emergency release last week.
> fix: substrate/dev dep, update changelog

- CHANGELOG.md
- package.json
- yarn.lock
* fix: substrate/dev dep, update changelog ([#632](https://github.com/paritytech/substrate-api-sidecar/pull/632)) ([8e8153f](https://github.com/paritytech/substrate-api-sidecar/commit/8e8153fac3dff037ba3de4678f511e064b9d7b74))
* fix: finalization for /blocks/head ([#631](https://github.com/paritytech/substrate-api-sidecar/pull/631)) ([8d0d538](https://github.com/paritytech/substrate-api-sidecar/commit/8d0d53831326f061dce9d111c3f16fd4084afc9b))
* docs(ChainType): fix docs for chaintype return value ([#626](https://github.com/paritytech/substrate-api-sidecar/pull/626)) ([f20b033](https://github.com/paritytech/substrate-api-sidecar/commit/f20b033d51f0e84bf869f056addd00db4c313f68))
> chore(release): 9.1.3

- CHANGELOG.md
- package.json
- yarn.lock
closes: [#636](https://github.com/paritytech/substrate-api-sidecar/issues/636)
Upgrade Priority: High
* Update @polkadot/api to 5.5.2 which fixes a critical bug with the `ParachainsInherentData` type.
> chore(release): 9.1.4

- src/controllers/paras/ParasController.ts
closes: [#640](https://github.com/paritytech/substrate-api-sidecar/issues/640)
Tested against polkadot, and kusama. 
Everything works on kusama as it should, and it gives the proper error message for polkadot.
> fix: add error message for chains that dont support parachains

- src/services/accounts/AccountsBalanceInfoService.spec.ts
- src/services/accounts/AccountsBalanceInfoService.ts
- src/services/test-helpers/mock/mockApi.ts
closes: [#634](https://github.com/paritytech/substrate-api-sidecar/issues/634)
This fixes historical queries for `/accounts/{accountId}/balance-info`.
> fix: historical queries for account balances

- CHANGELOG.md
- package.json
- yarn.lock
Important release for querying historical balance info
* Update `/accounts/{accountId}/balance-info` to correctly query historical blocks. ([#653](https://github.com/paritytech/substrate-api-sidecar/pull/653))([e9d7d7b](https://github.com/paritytech/substrate-api-sidecar/commit/e9d7d7b66549aeb0ca134d00183a30bb151e1a03))
> chore(release): 9.1.7

- .github/workflows/nodejs.yml
- .github/workflows/pr.yml
The latest version of wasm-pack v0.10.1 is causing a break in the CI due to file paths, so I set the version to 0.10.0 which resolves our issue.
> fix: workflows for wasm-pack

- README.md
- docs/src/openapi-v1.yaml
closes: [#670](https://github.com/paritytech/substrate-api-sidecar/issues/670)
Updates the version of substrate-api-sidecar inside of the docs, and also updates the release notes to update the docs.
> fix: update versioning in the docs

- docs/README.md
closes: [#669](https://github.com/paritytech/substrate-api-sidecar/issues/669)
This updates the readme for the open api docs.
> fix: update the readme for the open api docs

- .github/workflows/nodejs.yml
closes: [#673](https://github.com/paritytech/substrate-api-sidecar/issues/673)
Adds a CI test to build the docs to make sure there is no error.
> ci: build docs test

- CHANGELOG.md
- docs/src/openapi-v1.yaml
- package.json
- yarn.lock
PR for sidecar 9.1.10 release, Not going to merge yet until tests against Polkadot-derivative chains 9.10-rc4 pass when that's available
> chore(release): 9.1.10

- package.json
- yarn.lock
rel: [#680](https://github.com/paritytech/substrate-api-sidecar/issues/680)
This fixes the issue for @darwinian/types which is causing npm build issues for sidecar 9.1.10
> fix: fix api-sidecar npm package build

- .github/workflows/nodejs.yml
- package.json
- scripts/README.md
- scripts/config.ts
- scripts/runYarnPack.ts
- scripts/sidecarScriptApi.ts
- scripts/types.ts
Replaces: [#682](https://github.com/paritytech/substrate-api-sidecar/pull/682)
This PR is focused on adding a CI test to check if the npm release will work with a dry-run. The CI will run a script in sidecar called `runYarnPack.ts`. This scripts creates a Tarball, which is then used to install sidecar as a dep, the sidecar binary is then called and tested to see if it returns a successful response. After the test is over, it cleans its dep tree, and any additional files that are not native to the repo.
This PR will be followed by a part 2 where the newly abstracted script API will be applied to `runChainTests.ts`. I chose to not refactor that script in this PR in order to keep the PR's organized.
> ci: npm release check

- scripts/runChainTests.ts
- scripts/runYarnPack.ts
- scripts/sidecarScriptApi.ts
rel: [#684](https://github.com/paritytech/substrate-api-sidecar/pull/684)
This is a follow up to the PR mentioned above. It refactors the `runChainTests.ts` to use the scriptApi, and also lints and cleans up code in the scripts directory.
> fix: refactor e2e chain tests

- README.md
- package.json
- yarn.lock
This PR cleans up the resolutions and bumps `@polkadot/api` to v6.1.2
> fix(deps): bump polkadot/api, cleanup resolutions

- helm/templates/deployment.yaml
Recently we have received some alerts for substrate-api-sidecar application in production environment.
looking at the events of the container I see:
```
Warning  Unhealthy  39m                   kubelet  Readiness probe failed: Get "http://10.148.14.9:8080/": read tcp 10.148.14.1:46866->10.148.14.9:8080: read: connection reset by peer
Normal   Killing    36m (x12 over 33h)    kubelet  Container substrate-api-sidecar failed liveness probe, will be restarted
Normal   Started    35m (x13 over 4d20h)  kubelet  Started container substrate-api-sidecar
Normal   Pulled     35m (x12 over 33h)    kubelet  Container image "docker.io/parity/substrate-api-sidecar:v9.1.7" already present on machine
Normal   Created    35m (x13 over 4d20h)  kubelet  Created container substrate-api-sidecar
Warning …
```
> helm: increase liveness and rediness probe timeouts

- src/chains-config/metadata-consts/kusamaConsts.ts
- src/chains-config/metadata-consts/polkadotConsts.ts
- src/chains-config/metadata-consts/westendConsts.ts
- src/services/blocks/BlocksService.spec.ts
- src/services/blocks/BlocksService.ts
- src/services/test-helpers/mock/mockApi.ts
closes: [#690](https://github.com/paritytech/substrate-api-sidecar/issues/690)
This fixes a bug where when expanding metadata in order to capture the weights used in calculating we dont use the correct registry per historic block. This changes that to have a historicApi return the correct registry for the block.
> fix: expandMetadata for historic runtimes

- src/services/pallets/PalletsStorageService.ts
closes: [#694](https://github.com/paritytech/substrate-api-sidecar/issues/694)
The issue is reproducible querying kusama block 9509977:
`/pallets/democracy/storage/ReferendumInfoOf?key1=135&at=9509977`
This updates the metadata being used in pallets storage to the latest v13, this will be followed up by a PR to update it to v14, but because v14 will introduce breaking changes its important to patch the bug first then apply the changes after. I have a working version for v14, so there will be a follow up PR to this for the next major release.
> fix: error parsing metadata for pallets storage

- e2e-tests/endpoints/polkadot/runtime/metadata/6877002.json
- e2e-tests/endpoints/westend/blocks/5493461.json
- e2e-tests/endpoints/westend/blocks/5495855.json
- e2e-tests/endpoints/westend/runtime/metadata/7417678.json
`batch_calls_limited` in polkadot and westend, has an adjusted value.
Now that [ed389a4](https://github.com/paritytech/substrate-api-sidecar/commit/ed389a4baac99662321d2cf88f00669f9d6ce53d) and [4362347](https://github.com/paritytech/substrate-api-sidecar/commit/43623471913545d44ecea74e1411e4a1a740de53), we can update these two responses as they are no longer broken.
> test(e2e-tests): fix adjust values in e2e tests

- docs/src/openapi-v1.yaml
- src/services/accounts/AccountsVestingInfoService.spec.ts
- src/services/accounts/AccountsVestingInfoService.ts
- src/services/test-helpers/responses/accounts/vestingInfo789629.json
With runtime v9110, the vesting-info response now returns an array for `vesting`, with the `VestingInfo` type now being `Vec<PalletVestingVestingInfo>`. Sidecar previously returned responses under the `vesting` key as objects, therefore when there was no information the response was an empty object. 
This is now changed as the response will default to an empty array when there is no vesting-info on the account, and the past responses that were objects, will now be wrapped in an array. 
Before: 
```
{
"at": {
"hash": "0x89f4608b568a05a89737bc826a32f8677f2646a5773312d7dee3a667458e5a98",
"height": "6000000"
},
"vesting": {
"locked": "1749990000000000",
"perBlock": "166475460",
"startingBlock": "4961000"
}
}
```
After
```
{
"at": {
"hash": …
```
> fix!: change the response for vesting-info

- src/services/accounts/AccountsStakingInfoService.spec.ts
- src/services/accounts/AccountsStakingInfoService.ts
Add historicApi to staking info and reflect that in the tests. 
rel: [#698](https://github.com/paritytech/substrate-api-sidecar/issues/698)
> fix(StakingInfo): add historicApi to staking-info

- src/chains-config/metadata-consts/kusamaConsts.ts
- src/chains-config/metadata-consts/westendConsts.ts
Updates the blockWeights Store for both westend and kusama with the most up to date runtimes.
> fix: update blockWeights store for westend and kusama

- src/controllers/pallets/PalletsStorageController.ts
- src/services/pallets/PalletsStorageService.ts
This PR optimizes the `/pallets/{palletId}/storage/*` endpoints for V14 metadata by about a factor of 10. When using the `adjustMetadataV13` query parameter you will still experience slow load times. I also added a warning for the `adjustMetadataV13` query param when it's in use. The logged warning expresses that its subject to deprecation and will soon be removed. 
closes: [#730](https://github.com/paritytech/substrate-api-sidecar/issues/730)
> fix: optimize pallets-storage

- src/services/blocks/BlocksService.ts
closes: [#743](https://github.com/paritytech/substrate-api-sidecar/issues/743)
Updates the blocks endpoint to not fail when the connected chain doesn't have the session module to gather validators.
> fix: confirm session module before block retrieval

- e2e-tests/endpoints/kusama/blocks/8600000.json
- e2e-tests/endpoints/kusama/blocks/9000000.json
- e2e-tests/endpoints/kusama/blocks/9611378.json
- e2e-tests/endpoints/kusama/blocks/9625130.json
- e2e-tests/endpoints/kusama/blocks/9866423.json
- e2e-tests/endpoints/kusama/blocks/index.ts
- e2e-tests/endpoints/polkadot/blocks/6400003.json
- e2e-tests/endpoints/polkadot/blocks/6800002.json
- e2e-tests/endpoints/polkadot/blocks/7217908.json
- e2e-tests/endpoints/polkadot/blocks/7300000.json
- e2e-tests/endpoints/polkadot/blocks/index.ts
- e2e-tests/endpoints/westend/blocks/6200000.json
- e2e-tests/endpoints/westend/blocks/6800000.json
- e2e-tests/endpoints/westend/blocks/7200000.json
- e2e-tests/endpoints/westend/blocks/7600000.json
- e2e-tests/endpoints/westend/blocks/7800000.json
- e2e-tests/endpoints/westend/blocks/8000000.json
- e2e-tests/endpoints/westend/blocks/index.ts
This updates the e2e tests for blocks, and adds the most recent runtimes.
> fix: update e2e tests for blocks

- docs/src/openapi-v1.yaml
- e2e-tests/endpoints/kusama/paras/auctions-current/index.ts
- e2e-tests/endpoints/kusama/paras/crowdloan-info/index.ts
- e2e-tests/endpoints/kusama/paras/crowdloans/index.ts
- e2e-tests/endpoints/kusama/paras/lease-info/index.ts
- e2e-tests/endpoints/kusama/paras/leases-current/index.ts
- e2e-tests/endpoints/kusama/paras/paras/index.ts
- src/controllers/paras/ParasController.ts
This removes the `/paras/*` endpoints off of experimental. We are going to leave the `/experimental/*` endpoints for a little to give users ample amount of time to transition over.
> feat: transition `/paras/*` off of experimental

- .gitlab-ci.yml
Push-benchmark job didn't collect artifact, PR fixes this
> [ci] Fix push-benchmark job

- .gitlab-ci.yml
PR adds check of the result in the `check-benchmark` job.
Currently, the average benchmark result is ~9100ms, so I suggest to set threshold on 13000ms. If this threshold exceeds then the issue will be created in the [tracker](https://github.com/paritytech/substrate-api-sidecar/issues)
Closes https://github.com/paritytech/ci_cd/issues/174
> Add benchmark checker

- .gitlab-ci.yml
This is a CI infrastructure change.
The purpose of this PR is to update the benchmark CI job that uses a polkadot node.
We introduced `argo-cd` as an automation tool to maintain applications deployed on GKE and used a new name for the polkadot node:  [substrate-api-sidecar-benchmark](https://argocd.parity-build.parity.io/applications/substrate-api-sidecar-benchmark?view=tree&orphaned=false&resource=)
This is a job that use the new pod managed by argo: https://gitlab.parity.io/parity/mirrors/substrate-api-sidecar/-/jobs/1818316#L65
There are some [error messages](https://gitlab.parity.io/parity/mirrors/substrate-api-sidecar/-/jobs/1818316#L92)
but I've seen those in other jobs that were using the current polkadot node.
> ci: use polkadot node managed by argo-cd

- README.md
This updates the stability chart for Node.js versions, and sidecar support.
> docs: update node stability for versions

- src/services/blocks/BlocksService.ts
> fix: avoid use queryInfo rpc call

- src/services/node/NodeTransactionPoolService.spec.ts
Based on this [comment](https://github.com/paritytech/substrate-api-sidecar/pull/1177#issuecomment-1374012586), I just removed the calls & the corresponding imports.
> test: removed rpc.payment call from nodeTxPool spec file

- src/services/node/NodeTransactionPoolService.spec.ts
- src/services/node/NodeTransactionPoolService.ts
- src/services/test-helpers/mock/mockApi.ts
- src/services/test-helpers/responses/node/transactionPoolWithTipOperational.json
- src/services/transaction/TransactionFeeEstimateService.spec.ts
This replaces the rpc calls with runtime calls, and fizes the bug for weights, regarding both weights v1, and weights v2.
closes: https://github.com/paritytech/substrate-api-sidecar/issues/1153
> fix: replace rpc calls for fees and give support for weight v1 and v2

- package.json
- yarn.lock
Updates the following deps:
"@polkadot/api": "^9.11.1",
"@polkadot/api-contract": "^9.11.1",
"@polkadot/util-crypto": "^10.2.3",
> chore(deps): update polkadot-js api, and util-crypto

- package.json
- yarn.lock
Closes: #1196 
As an additional note, the `confmgr` repo was moved from Gitlab to Github and below are the corresponding links : 
-   repo: [https://github.com/chevdor/confmgr](https://github.com/chevdor/confmgr)
-   doc: [https://chevdor.github.io/confmgr/](https://chevdor.github.io/confmgr/)
-   package: [https://www.npmjs.com/package/confmgr](https://www.npmjs.com/package/confmgr)
> chore: updated to new version of confmgr

- package.json
- src/services/blocks/BlocksService.ts
- src/services/node/NodeTransactionPoolService.ts
- src/services/transaction/TransactionFeeEstimateService.ts
- yarn.lock
Now with the newest version of Polkadot-js, the Weight types are more narrowed and specified, we have to account for WeightsV1 and WeightsV2 when parsing the data. This PR resolves that while updating to the latest polkadot-js deps
> chore(deps): update polkadot-js deps

- package.json
- yarn.lock
Updates polkadot-js to the most recent patch to fix a small bug regarding blocks near genesis.
> chore(deps): update polkadot-js api to most recent patch

- src/logging/consoleOverride.ts
This cleans up some technical debt around type assignment for our `consoleOverride`.
> chore(tech-debt): cleanup type assignment for `consoleOverride`

- jest.config.js
- package.json
- yarn.lock
Updates the following deps:
"@polkadot/api": "^9.13.6",
"@polkadot/api-contract": "^9.13.6",
Also updates the jest config to fix the following error:
```
jest-haste-map: Haste module naming collision: @substrate/api-sidecar
The following files share their name; please adjust your hasteImpl:
* <rootDir>/package.json
* <rootDir>/build/package.json
```
> chore(deps): update pjs deps

- .gitlab-ci.yml
PR adds e2e tests to CI
Close https://github.com/paritytech/ci_cd/issues/734
> ci: add e2e tests to ci

- .gitlab-ci.yml
- Dockerfile.README.md
This PR adds CI job to publish docker image description to hub.docker.com
Dockerfile.README.md content just copy/paste from main README.md docker section. Feel free to propose changes.
Subtask of https://github.com/paritytech/ci_cd/issues/741
> ci: add docker image description publishing

- .gitlab-ci.yml
Resolves https://github.com/paritytech/ci_cd/issues/774.
> CI: Allow GitLab E2E test jobs to fail

- scripts/config.ts
Changes all the historical e2e-tests node endpoints to ones hosted by parity.
> test(scripts): change historical e2e-tests endpoints to parity hosted nodes

- src/services/blocks/BlocksService.ts
closes: https://github.com/paritytech/substrate-api-sidecar/issues/1264
For more detail please refer the issue above:
Summary: Our caching mechanism was storing unfinalized block heads and once they were finalized returning the older value which is incorrect, so in this PR we are ensuring that if the cached block is not finalized to re-query the block. NOTE: there is room for optimization but for now this is a solution to get rid of the bug.
> fix: incorrect finalization when head blocks are cached and polled

- package.json
- yarn.lock
This mainly updates all the jest and eslint deps. This should increase performance and keep dependencies up to date.
> chore(deps): update substrate dev

- e2e-tests/latest/endpoints/acala.ts
- e2e-tests/latest/endpoints/index.ts
- e2e-tests/latest/endpoints/karura.ts
- e2e-tests/latest/endpoints/statemint.ts
- e2e-tests/latest/index.ts
- package.json
- yarn.lock
- Added `ts-node` to dev deps so I can run it with `yarn ts-node src/main.ts` and run e2e tests with `yarn ts-node e2e-tests/latest/index.ts`. There is no reason to build before run if we can just run it.
- Updated the e2e tests output so it is less confusing.
- Some code refactoring
- Added Acala & Karura e2e tests
- Allow config sidecar url for e2e test
- Fix exit code
> test: add acala & karura to e2e tests and some improvements

- .github/workflows/pr.yml
GitHub is going to deprecate `save-state` and `set-output` commands. [More info](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
This PR adjusts GHA workflow to use new syntax.
Part of https://github.com/paritytech/ci_cd/issues/805
> CI: fix gha set-output command

- package.json
- src/test-helpers/typeFactory.ts
- yarn.lock
- Updated packages:
```
"@polkadot/api": "^10.9.1",
"@polkadot/api-contract": "^10.9.1",
"@polkadot/util-crypto": "^12.3.2",
```
- Replaced `Constructor` with `CodecClass` 
I did this change because after updating the dependencies and building again with `yarn build`, I would get this error
```
**src/test-helpers/typeFactory.ts:24:2 - error TS2305: Module '"@polkadot/types/types"' has no exported member   'Constructor'.
Found 1 error in src/test-helpers/typeFactory.ts:24**
```
With the change, it builds and tests passes.
The tests that still fail are the latest e2e (`yarn test:latest-e2e-tests`) when I connect to `Westend`. These tests fail even without updating the dependencies. It might be related to the current issues that the Westend Chain faces (?).
> fix(deps): update pjs api

- scripts/README.md
- scripts/config.ts
- scripts/runHistoricalE2eTests.ts
- scripts/runLatestE2eTests.ts
The changes in this PR are the following : 
1. Replaced the `wsUrl` endpoints with `asset-hub`
2. Replaced `asset-hub-<relay_chain>` to `<relay_chain>-asset-hub` strictly in the places that is `user-facing`
since : 
1. the `wsUrl` endpoints were also updated in polkadot-js/apps PR [#9526](https://github.com/polkadot-js/apps/pull/9526/files) (so we could replace one of the two exceptions from this PR [#1296](https://github.com/paritytech/substrate-api-sidecar/pull/1296) )
2. based on the feedback from Joe whatever is related to internal structure we keep as `AssetHub<Relay>` or `asset-hub-<relay>` and whatever is related to the "user" should be in the format `<relay>-asset-hub`.
I made the 2nd change with the assumption that `user` is also someone who is running the tests. If this …
> fix: rename wsurl endpoints to asset hub

- src/services/blocks/BlocksService.ts
The whole thing needs a refactoring so that the usage of API (i.e. fetchQueryInfo) is not detached to the API detection code but I don't all the time to do it so will just do the quick fix for now.
> fix: query info feature detection

- package.json
- yarn.lock
This solves the current CI errors we are getting with all the dev scripts.
It just updates the types for express.
> test(fix-dev): update appropriate type packages

- e2e-tests/historical/endpoints/kusama/runtime/spec/10000.json
- e2e-tests/historical/endpoints/kusama/runtime/spec/100000.json
- e2e-tests/historical/endpoints/kusama/runtime/spec/2000000.json
- e2e-tests/historical/endpoints/kusama/runtime/spec/4000000.json
- e2e-tests/historical/endpoints/kusama/runtime/spec/8000000.json
- e2e-tests/historical/endpoints/polkadot/runtime/spec/1000.json
- e2e-tests/historical/endpoints/polkadot/runtime/spec/200000.json
- e2e-tests/historical/endpoints/polkadot/runtime/spec/3000000.json
- e2e-tests/historical/endpoints/polkadot/runtime/spec/6877002.json
- e2e-tests/historical/endpoints/westend/runtime/spec/10000.json
- e2e-tests/historical/endpoints/westend/runtime/spec/2000000.json
- e2e-tests/historical/endpoints/westend/runtime/spec/7417678.json
- e2e-tests/jest.config.js
- src/sanitize/sanitizeNumbers.ts
This PR includes 3 separate fixes :
1. Add check in sanitize numbers for Bifrost object type
2. Add entry `isEthereum` in test results
3. Small fix in jest config
Relates to issue https://github.com/paritytech/substrate-api-sidecar/issues/1082
When connected to `wss://bifrost-rpc.liebi.com/ws` and requesting one of the following blocks
- `2652989`
- `3460065`
-  [5296330](https://bifrost-kusama.subscan.io/block/5296330) 
- [5296335](https://bifrost-kusama.subscan.io/block/5296335) 
Sidecar returns the message : 
```
"Unexpected non-string and non-number key while sanitizing a Map-like type"
```
This is because the `delegations` entry have as `key` a `Multilocation` object and in Sidecar code when we sanitize [here](https://github.com/paritytech/substrate-api-sidecar/blob/8fa49aaa93cfdad36f …
> fix: bifrost type issue & small fixes in tests

- .github/workflows/gitspiegel-trigger.yml
Using a workflow to trigger mirroring instead of a webhook allows us to reuse "Approving workflow runs from public forks" GitHub feature to somewhat protect us from malicious PRs
> ci: adding gitspiegel-trigger workflow

- .github/workflows/gitspiegel-trigger.yml
The first attept to use a workflow to protect GitLab CI from untrusted contributors failed, because GitHub doesn't pass secrets to workflows for PRs that originate from forks. 
This uses a different approach: instead of triggerring gitspiegel API directly from the workflow, we're just spawning an empty workflow with a specific path, and gitspiegel listens for `workflow_run` event to start mirroring.  
The idea is the same: for the first-time contributors, running workflows would require manual aciton and that would block mirroring. But this time, we don't need any secrets to make it work.
> ci: fixing gitspiegel trigger workflow

- src/services/accounts/AccountsBalanceInfoService.spec.ts
- src/services/accounts/AccountsBalanceInfoService.ts
- src/services/test-helpers/responses/accounts/balanceInfoFeeFrozen.json
closes: https://github.com/paritytech/substrate-api-sidecar/issues/1262
> test: add test for frozen deprecation in runtime

- Dockerfile
- package.json
- yarn.lock
This updates the node version to 18.12.1, and wasm-pack to 0.12.1.
The minimum version for node in sidecar is 18.x.x.
This will help resolve: https://github.com/paritytech/substrate-api-sidecar/pull/1358
> ci: update node version in docker, and wasm-pack

- e2e-tests/latest/endpoints/polkadot.ts
- src/services/pallets/PalletsConstantsService.ts
- src/services/pallets/PalletsDispatchablesService.ts
- src/services/pallets/PalletsErrorsService.ts
- src/services/pallets/PalletsEventsService.ts
- src/services/pallets/PalletsStorageService.ts
This PR replaces the `e2e/latest` tests that are pointing to deprecated pallets. 
The [polkadot runtime](https://github.com/polkadot-fellows/runtimes/blob/5d98c2efcdb61a90e5a325c80b6c5d2b2c1d6625/relay/polkadot/src/lib.rs#L1375) no longer has :
- the `Democracy` pallet with index 14
- the `PhragmenElection` pallet with index 17
The pallets and their indices can be found in previous versions of the polkadot runtime, e.g. [Democracy](https://github.com/paritytech/polkadot/blob/1ed6e2e50a4ce61f6cda46a730efc11a07b6ebb3/runtime/polkadot/src/lib.rs#L1374) and [PhragmenElection](https://github.com/paritytech/polkadot/blob/1ed6e2e50a4ce61f6cda46a730efc11a07b6ebb3/runtime/polkadot/src/lib.rs#L1377C17-L1377C17).
Instead of removing completely the tests I replaced them so they point to existing …
> test(e2e): replace tests pointing to deprecated pallets

- src/services/blocks/BlocksService.ts
This ensures no Promises are made when they are not needed.
> perf: transactionPaidFee event optimization

- src/controllers/blocks/BlocksController.ts
- src/services/blocks/BlocksService.ts
This adds concurrency to the extrinsic calls, with a task queue of 4 calls running concurrently.
Given the previous regression this was able to bring the request time from 70s to 26s.
Along with https://github.com/paritytech/substrate-api-sidecar/pull/1367, requests are now down to 3s or less.
> perf: add concurrency to fee calls

- src/chains-config/index.ts
This ensure all specNames are supported for the asset hub chains.
> fix: ensure statemine, and statemint are still supported

- benchmarks/README.md
- benchmarks/blocksBlockId/benchHighLoadBlocks.lua
- benchmarks/blocksBlockId/blocks.lua
- benchmarks/blocksBlockId/highLoadBlocks.lua
- benchmarks/blocksBlockId/highLoadInit.sh
This PR adds the ability for us to measure how sidecar reacts to highloads for the `/blocks` endpoint. High load in this context specifically refers to a large amount of extrinsics.
> perf: add additional high load benchmarks for `/blocks`

- src/services/accounts/AccountsStakingPayoutsService.ts
In `staking-payouts` endpoint, the `claimed` field is returning `false` even when rewards are actually claimed.
The `claimed` variable is set in this [line](https://github.com/paritytech/substrate-api-sidecar/blob/b2aab7dd5ae93b1270e8baba4e2ac7e0c8d3e8ed/src/services/accounts/AccountsStakingPayoutsService.ts#L279) of code where we check if the requested `eraIndex` is included in the `claimedRewards` vector. After testing, it shows that the `includes` function does not work as expected and does not return `true` when the `eraIndex` is included in the array. The reason might be related to types because I tried to use `includes` when changed the type of the eraIndex and it returned `true`. However this is still weird because if I check :
- `validatorLedger.claimedRewards.toRawType()` -> it …
> fix: changed how claimed variable is set in staking-payouts

- src/services/blocks/BlocksService.ts
When we request a block in Sidecar with a query param set to a specific value, e.g. :
`/blocks/1820744?extrinsicDocs=false` : _return block and show the docs in each extrinsic_
and right away I request again the same block but now with the query param set to a different value, e.g. :
`/blocks/1820744?extrinsicDocs=true` : _return block and do **not** show the docs in each extrinsic_
the response is not updated so it still doesn't show me the docs in each extrinsic.
This happens because of how we cache the response. Wen we cache the block [here](https://github.com/paritytech/substrate-api-sidecar/blob/aef22fe4bb1660058b71c302b7ee15068ef64d32/src/services/blocks/BlocksService.ts#L206) we set the key in the cache "array" equal to the block hash. So when we request again the same block it …
> fix: generated a custom key for the cache in blocks endpoint

- src/chains-config/assetHubKusamaControllers.ts
Now that the asset-conversion pallet is available on KAH, this is just adding the endpoints for that chain.
Related to #1322
> fix: add asset conversion pallet to Kusama Asset Hub

- .gitlab-ci.yml
Issue: https://github.com/paritytech/devops/issues/2977
`helm deploy` command was replaced by `argocd set/sync` command
> ci: Replace helm deploy with argo cd

- src/services/accounts/AccountsStakingPayoutsService.ts
This resolves an error where legacy blocks on Kusama would throw an error:
```
{
"code": 500,
"message": "Cannot read properties of undefined (reading 'indexOf')",
"stack": "TypeError: Cannot read properties of undefined (reading 'indexOf')\n    at AccountsStakingPayoutsService.deriveEraPayouts (/Users/tarikgul/Desktop/parity/tools-team/substrate-api-sidecar/src/services/accounts/AccountsStakingPayoutsService.ts:293:79)\n    at /Users/tarikgul/Desktop/parity/tools-team/substrate-api-sidecar/src/services/accounts/AccountsStakingPayoutsService.ts:170:50\n    at Array.map (<anonymous>)\n    at AccountsStakingPayoutsService.fetchAccountStakingPayout (/Users/tarikgul/Desktop/parity/tools-team/substrate-api-sidecar/src/services/accounts/AccountsStakingPayoutsService.ts:170:28)\n    at …
```
> fix: staking-payouts for legacy kusama node

- package.json
- yarn.lock
Updated the following dependencies to new `patch` versions: 
- `express` (dep)
- `@types/argparse` (devDep)
- `@types/express` (devDep)
- `@types/express-serve-static-core` (devDep)
- `@types/morgan` (devDep)
- `@types/triple-beam` (devDep)
Updated the following dependencies to new `minor` versions:
- `rxjs` (dep) - [changes shown in commits](https://github.com/ReactiveX/rxjs/commits/master/)
- `winston` (dep) - [changes mentioned in release notes](https://github.com/winstonjs/winston/releases)
> chore(deps): update non pjs deps

- src/services/pallets/PalletsForeignAssetsService.spec.ts
- src/services/pallets/PalletsForeignAssetsService.ts
- src/services/test-helpers/mock/assets/mockAssetHubKusamaData.ts
The endpoint `pallets/foreign-assets` throws the following error:
```
{
"code": 500,
"message": "createType(XcmV3MultiLocation):: DoNotConstruct: Cannot construct unknown type XcmV3MultiLocation",
"stack": "Error: createType(XcmV3MultiLocation):: DoNotConstruct: Cannot construct unknown type XcmV3MultiLocation\n    at createTypeUnsafe ...",
"level": "error"
}
```
The error is thrown when it tries to create the `XcmV3MultiLocation` type in this [line](https://github.com/paritytech/substrate-api-sidecar/blob/96c9f11d7c4142c6f8a145eb932fb650941ade50/src/services/pallets/PalletsForeignAssetsService.ts#L60).
First try to create the `StagingXcmV3MultiLocation` type and if it is not successful try the `XcmV3MultiLocation` type.
Tested the endpoint by connecting to Polkadot/Kusama/Rococo Asset …
> fix: multilocation type in pallets/foreign-assets

- src/controllers/accounts/AccountsStakingPayoutsController.ts
- src/services/accounts/AccountsStakingPayoutsService.ts
Added a check to determine if we are connected in the Kusama chain, as the calculations are `Kusama` specific.
> fix: add Kusama chain check in historic blocks

- package.json
- src/services/accounts/AccountsStakingPayoutsService.ts
- src/services/pallets/PalletsAssetConversionService.spec.ts
- src/services/paras/ParasService.ts
- src/services/test-helpers/mock/data/assetConversionEntries.ts
- src/types/responses/AccountStakingInfo.ts
- src/types/responses/PalletAssetConversion.ts
- yarn.lock
Updated the following dependencies : 
- `@polkadot/api`
- `@polkadot/api-contract`
Replaced:
- `PalletStakingExposure` with `SpStakingExposure`
- `XcmV3MultiLocation` with `StagingXcmV3MultiLocation` 
- _Note: In `assetConversionEntries.ts` when [createType](https://github.com/paritytech/substrate-api-sidecar/blob/6028086ee3e236476c7b7ce5a8db4efe50875e7d/src/services/test-helpers/mock/data/assetConversionEntries.ts#L24) is called, it is left as `XcmV3MultiLocation` (since in `assetHubWestendRegistryV9435` there is no `StagingXcmV3MultiLocation` )_
- `PolkadotPrimitivesV5CandidateReceipt` with `PolkadotPrimitivesV6CandidateReceipt`
- `RewardDestination` with `Option<PalletStakingRewardDestination>`
- `PalletAssetConversionNativeOrAssetId` with …
> fix(deps): update pjs deps, and fixing types

- src/controllers/accounts/AccountsStakingPayoutsController.ts
Closes #1421 
In #1415 a new variable `isKusama` was added to ensure that Kusama specific calculations are _activated_ / _taking effect_ only if we are connected to the Kusama chain. 
However, with this change the variable `sanitizedDepth` was left `undefined` if 
- the query param `depth` had a valid value and
- we were connected to any other chain
The reason is this [line](https://github.com/paritytech/substrate-api-sidecar/blob/master/src/controllers/accounts/AccountsStakingPayoutsController.ts#L116) of code:
```
if (depth && isKusama) {
sanitizedDepth = Math.min(Number(depth), currentEra - 518).toString();
}
```
where `sanitizedDepth` is defined only is `depth` has a value and we are connected to the Kusama chain.
Added a small fix to correct this.
> fix: define query param depth in Staking Payouts for all chains

- docs/src/openapi-v1.yaml
- src/controllers/paras/ParasController.ts
- src/services/paras/ParasService.ts
Rel: #1413 
With the introduction of Coretime, all endpoints related to parachains (`paras`): crowdloans, leases, auctions, etc. will be phased out. Hence, a deprecation note has been added (docs, controller and service file) to the following endpoints:
- `/paras`
- `/paras/leases/current`
- `/paras/auctions/current`
- `/paras/crowdloans`
- `/paras/{paraId}/crowdloan-info`
- `/paras/{paraId}/lease-info`
- `/paras/head/included-candidates`
- `/paras/head/backed-candidates`
> fix: add deprecation note for paras endpoints

- src/services/accounts/AccountsStakingPayoutsService.ts
In the `/accounts/{accountId}/staking-payouts` endpoint, for some accounts if we query : 
1. at a specific `era`and at a sample block height, e.g. 1400000 we do **not** get any payouts for the account
2. but then if we query at the same `era` but 100k blocks later, e.g. 1500000 we do get payouts for that same account
**1. endpoint**
```
http://127.0.0.1:8080/accounts/GeYJhboY5bEc5WZFbrdxhEF9m6Y4NnbKzfCu1rBHxGWgviK/staking-payouts?at=1475279&depth=1&era=518&unclaimedOnly=false
```
era= 518
block = 1475279
**response**
```
{
"at": {
"height": "1475279",
"hash": "0x41798cccf4575dac192c8783925084fa50d8d84a024782f02c3740f857ea47a0"
},
"erasPayouts": [
{
"era": "518",
"totalEraRewardPoints": "56520",
"totalEraPayout": "903617559682178",
"payouts": []
}
]
}
```
**2. endpoint**
``` …
```
> fix: staking payouts change claimed value

- src/services/accounts/AccountsStakingPayoutsService.ts
Rel: https://github.com/paritytech/substrate-api-sidecar/issues/1411
The changes in this PR are affecting the responses returned by `/accounts/{accountId}/staking-payouts` endpoint.
After the runtime upgrade of Polkadot to [v1.2.0](https://github.com/polkadot-fellows/runtimes/releases/tag/v1.2.0), the new storage items `erasStakersPaged` and `erasStakersOverview` are used instead of `erasStakersClipped`. 
More information regarding this change can be found: 
- https://github.com/paritytech/polkadot-sdk/pull/1189
- https://github.com/polkadot-js/apps/issues/10004
Hence, as mentioned [here](https://github.com/paritytech/polkadot-sdk/issues/433), to get the rewards: 
- in Kusama after era 6514 (Apr 18) and
- in Polkadot after era 1420 (Apr 21)
we need to make use of the new storage items …
> fix: add new staking storage items

- CHANGELOG.md
- docs/src/openapi-v1.yaml
- package.json
- PR https://github.com/paritytech/substrate-api-sidecar/pull/1432 is under the `breaking changes` section. Although it maintains backward compatibility, it does modify the endpoint's response compared to the previous state (before the enactment of the related runtime upgrade).
- Similarly, PR https://github.com/paritytech/substrate-api-sidecar/pull/1429 is labeled as a `breaking change` due to the fact that it also changing the response provided to users compared to previous Sidecar versions.
- PR https://github.com/paritytech/substrate-api-sidecar/pull/1422 is quite an important fix.
> chore(release): 19.0.0

- src/chains-config/assetHubPolkadotControllers.ts
Now that the asset-conversion pallet is available on PAH, this is just adding the endpoints for that chain.
Closes #1322
> fix: add asset conversion pallet to Polkadot Asset Hub

- src/services/accounts/AccountsStakingPayoutsService.spec.ts
- src/services/accounts/AccountsStakingPayoutsService.ts
Closes https://github.com/paritytech/substrate-api-sidecar/issues/1438
This PR fixes duplicate payouts found in the `accounts/<address>/staking-payouts` endpoint when querying some specific cases of nominators.
In certain rare cases (eras `6xx`), a single nominator may have multiple nominations for the same validator and at the same era, each with a different stake amount.
In Sidecar we were not expecting to have this case. We were expecting one stake of a nominator per validator, not multiple. Consequently :
- When we print payouts we iterate through a list that has now 2 entries of the same validator instead of one. That is why we get twice the same validator in the response.
- And then, for these two entries, the payout calculations are based on the first stake that we find and not the …
> fix: duplicate payouts in staking-payouts endpoint

- README.md
- package.json
- yarn.lock
Updated the following polkadot-js dependencies : 
- `@polkadot/api`
- `@polkadot/api-contract`
to latest version [v11.1.1](https://github.com/polkadot-js/api/releases/tag/v11.1.1)
Updated also the corresponding [section](https://github.com/paritytech/substrate-api-sidecar?tab=readme-ov-file#updating-polkadot-js-dependencies) in the README.
> chore(deps): update polkadot-js deps & README

- e2e-tests/historical/endpoints/kusama/accounts/staking-info/10819301.json
- e2e-tests/historical/endpoints/kusama/accounts/staking-info/11000000.json
- e2e-tests/historical/endpoints/kusama/accounts/staking-info/11100000.json
- e2e-tests/historical/endpoints/kusama/accounts/staking-info/11500000.json
- e2e-tests/historical/endpoints/kusama/accounts/staking-info/11800000.json
- e2e-tests/historical/endpoints/kusama/accounts/staking-info/1500000.json
- e2e-tests/historical/endpoints/kusama/accounts/staking-info/3000000.json
- e2e-tests/historical/endpoints/kusama/accounts/staking-info/5000000.json
- e2e-tests/historical/endpoints/kusama/accounts/staking-info/8000000.json
- e2e-tests/historical/endpoints/kusama/accounts/staking-info/9500000.json
- e2e-tests/historical/endpoints/kusama/accounts/staking-info/9894877.json
- e2e-tests/historical/endpoints/polkadot/accounts/staking-info/1000000.json
- e2e-tests/historical/endpoints/polkadot/accounts/staking-info/3000000.json
- e2e-tests/historical/endpoints/polkadot/accounts/staking-info/350000.json
- e2e-tests/historical/endpoints/polkadot/accounts/staking-info/6000000.json
- e2e-tests/historical/endpoints/polkadot/accounts/staking-info/7000000.json
- e2e-tests/historical/endpoints/polkadot/accounts/staking-info/7472552.json
- e2e-tests/historical/endpoints/polkadot/accounts/staking-info/8000000.json
- e2e-tests/historical/endpoints/polkadot/accounts/staking-info/8320000.json
- e2e-tests/historical/endpoints/polkadot/accounts/staking-info/8500000.json
- e2e-tests/historical/endpoints/polkadot/accounts/staking-info/9000000.json
- e2e-tests/historical/endpoints/polkadot/accounts/staking-info/9500000.json
- e2e-tests/historical/endpoints/westend/accounts/staking-info/6000000.json
- e2e-tests/historical/endpoints/westend/accounts/staking-info/8041521.json
- src/services/accounts/AccountsStakingInfoService.ts
- src/services/test-helpers/responses/accounts/stakingInfo789629.json
- src/types/responses/AccountStakingInfo.ts
Closes https://github.com/paritytech/substrate-api-sidecar/issues/1446
This PR adds the field `nominations` in the `staking-info` endpoint's response which was missing. This information is retrieved from the [api.query.staking.nominators](https://polkadot.js.org/docs/kusama/storage#nominatorsaccountid32-optionpalletstakingnominations) call.
When connected to the Polkadot chain, the following request
`http://127.0.0.1:8080/accounts/16GMHo9HZv8CcJy4WLoMaU9qusgzx2wxKDLbXStEBvt5274B/staking-info?at=20300500`
results in the response below:
```
{
"at": {
"hash": "0xfee9a90faaaa0e29f3feb53360bf8527ffdfa295267602b35ed8990bf01d5493",
"height": "20300500"
},
"controller": "16eM1npMwKzpGy48NDna1jC6P71S783wjpbdeKT8RgzQx8Jd",
"rewardDestination": {
"account": …
```
> fix: add nominations in staking-info endpoint

- CHANGELOG.md
- docs/src/openapi-v1.yaml
- package.json
This release is a `patch` release because it includes:
- multiple `chore` related PRs
- one fix in the `staking-info` endpoint
- an update of the pjs dependencies from `v11.1.1` to `v12.0.1`
1. The pjs-api release [v12.0.1](https://github.com/polkadot-js/api/releases/tag/v12.0.1) introduced the possibility to add the `CheckMetadataHash` signed extension and was considered a major release. However, in the Sidecar side, it is considered as a regular dependency update since the usage of endpoints remains unchanged.
2. Having said that, since this a very important addition in pjs-api I could also mention it as a Note in the release notes of Sidecar. 
3. In the `Compatibility` section of the `Changelog` (and subsequently in the release notes later), I changed the node version format. Based on …
> chore(release): 19.0.2

- README.md
- guides/MAINTENANCE.md
Adding this guide to outline the tasks required from the maintainer of this tool. 
It is based on my experience of performing maintenance tasks over the last months during which I received valuable input from @TarikGul 💯
> docs: add maintenance guide

- README.md
Removed the old stable version release note since it is not relevant anymore (circa 4 years old).
> docs: Remove old stable version note

- CHANGELOG.md
- docs/src/openapi-v1.yaml
- package.json
This is a `minor` release for Sidecar since: 
- it includes features and updates in docs and dependencies and
- in the pjs and non pjs deps no breaking change was identified 
In the compatibility section (CHANGELOG), I reverted the node version in the previous format. Also, added in parenthesis the node release in the format (vX.XX.XX) as it appears on the Polkadot [releases](https://github.com/paritytech/polkadot-sdk/releases) page to avoid any confusion.
> chore(release): 19.1.0

- src/services/accounts/AccountsAssetsService.ts
- src/services/accounts/AccountsPoolAssetsService.ts
- src/services/accounts/AccountsStakingPayoutsService.ts
- src/services/blocks/BlocksService.ts
- src/services/pallets/PalletsStakingProgressService.ts
It slightly improves the performance of the blocks controller by injecting the historic api to calculate the fees removing two extra promises per extrinsic.
It improves the single block query by ~15% (tested on large blocks in different chains) and also improves the response time on range queries by ~10%. On large ranges > 200 blocks, the improvement reduces as I believe it becomes more of a memory issue.
We should probably have a discussion on what to do with the range query, since if extrinsics/block will increase, that specific query will become slower, even if performance is further improved.
> fix: Improve performance of blocks service by dependency injection

- .github/dependabot.yml
Fix in dependabot yaml file that:
- Adds the prefix `chore(deps):` in the PR title since all dependabot PRs are deps updates
- Removed the `scope` since this often opens a PR with a title prefix `chore:(deps):` instead of `chore(deps):`
- Adds the `D0 - Dependencies` label in the PR 
This solves the issues of:
- having to manually change the prefix of the PR's title whenever a PR is not identified as a dependency from dependabot (example found [here](https://github.com/paritytech/substrate-api-sidecar/pull/1451))
- not finding the label `dependencies` (example found [here](https://github.com/paritytech/substrate-api-sidecar/pull/1451#issuecomment-2164675846))
> fix: dependabot yaml

- src/controllers/AbstractController.ts
- src/controllers/blocks/BlocksController.ts
- src/controllers/blocks/BlocksExtrinsicsController.ts
- src/controllers/blocks/BlocksRawExtrinsicsController.ts
- src/services/blocks/BlocksService.spec.ts
- src/services/blocks/BlocksService.ts
This PR decreases the memory consumption produced by the LRU cache in the blocks Service by moving it to the Blocks controllers and use it only for the necessary endpoints, rather than on all fetchBlock calls. It also slightly improves response times on those endpoints by not checking the cache for every single block.
The PR also makes sure that the reference to promises in the arrays are removed by setting the array length to 0. 
Local tests have shown improvement in the Promise store in heap memory which now stays constant.
To test locally, I have run a benchmark script to hit the BlocksController with range queries. It allows to check how the endpoint behaves with large queries.
While the initial LRU Cache was increasing in size as a larger range was queried, with the current set up …
> fix: Moves the LRUcache to Controller level

- docs/package.json
- docs/yarn.lock
- package.json
- yarn.lock
Noticeable upgrade is that of `lru-cache` from `^10.4.3`to `^11.0.1` so major upgrade due to this [change](https://github.com/isaacs/node-lru-cache/issues/352). No issues though on Sidecar side.
> chore(deps): update non pjs deps & in docs

- CHANGELOG.md
- docs/src/openapi-v1.yaml
- package.json
This is a `minor` release for Sidecar since: 
- it includes features and updates in docs and dependencies and
- the major bump of the pjs libraries to [v13.X.X](https://github.com/polkadot-js/api/releases) should not have a breaking change effect in Sidecar
> chore(release): 19.2.0

- src/services/transaction/TransactionFeeEstimateService.ts
Rel https://github.com/paritytech/substrate-api-sidecar/issues/1504
Tested it while running SIdecar locally connected to Polkadot chain and calling the `fee-estimate` endpoint with a test transaction as shown below : 
```
curl -X 'POST' \
'http://127.0.0.1:8080/transaction/fee-estimate' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '{
"tx": "0x59028400d172a74cda4c865912c32ba0a80a57ae69abae410e5ccb59dee84e2f4432db4f00411581e00421c087e27123c781bf9c287aae4a3b58f649d31fb3b587094c9bfc99e65ed1e91ca2bfa7e1c2f8e95e2cbdff29fa16bd092c8b2bb39be3ca696b0d00040208af2f000503005665ef9894f68738853586822941e372b30a1e621bda3f5698effd4a5e581f31137cf0010c343237a8"
```
which returns
```
{"weight":{"refTime":"145570000","proofSize":"3593"},"class":"Normal","partialFee":"163154905"} …
```
> fix: queryInfo call in fee-estimate endpoint

- src/App.ts
Rel https://github.com/paritytech/substrate-api-sidecar/issues/1508
Due to the upgrade in Express 5, we need to adjust how the router is accessed. 
Run Sidecar from the latest release and check  
```
http://127.0.0.1:8080
```
in your browser or with curl from your terminal
> fix: how to access router in getRoutes

- CHANGELOG.md
- docs/src/openapi-v1.yaml
- package.json
Patch release that fixes an issue introduced in v19.2.1, caused by the upgrade to Express v5.0.0.
> chore(release): 19.2.2

- RELEASE.md
- guides/MAINTENANCE.md
- src/App.ts
The endpoint `/accounts/{accountId}/asset-balances` no longer returns results for specific assets which means that the array query param format `?assets[]=1&assets[]=2&assets[]=3`does not work as expected. 
The `assets[]` array query params are also used in: 
- `/accounts/{accountId}/pool-asset-balances`
and other endpoints are using array query params and are probably affected but haven't tested them: 
- `/pallets/{palletId}/storage/{storageItemId}`
- `/contracts/ink/{address}/query`
This issue is due to the upgrade from Express v4 to v5. In order to correctly handle `[]` in query params in `v5`, we need to set the default parser to `extended` (related [resource](https://github.com/expressjs/express/issues/5060)).
You can test that this change fixes the issue when connected to Polkadot …
> fix: filtering in assets endpoint & update guides

- package.json
- yarn.lock
Updated polkadot-js dependencies to the latest version, [v14.0.1](https://github.com/polkadot-js/api/releases/tag/v14.0.1).
> chore(deps): update polkadot-js deps to `v14.0.1`

- docs/README.md
- guides/CONTRIBUTING.md
- package.json
- src/services/paras/ParasService.ts
- yarn.lock
- Updated polkadot-js dependencies to latest versions.
- Updated corresponding guide & README with detailed instructions on how to update Sidecar documentation.
Updating the deps is needed in order to test this [PR](https://github.com/paritytech/substrate-api-sidecar/pull/1520).
> chore(deps): update polkadot-js deps & guides

- docs/src/openapi-v1.yaml
- src/controllers/transaction/TransactionDryRunController.ts
- src/services/test-helpers/mock/mockAssetHubWestendApi.ts
- src/services/test-helpers/mock/mockDryRunCall.ts
- src/services/transaction/TransactionDryRunService.spec.ts
- src/services/transaction/TransactionDryRunService.ts
- src/types/requests.ts
- src/types/responses/TransactionDryRun.ts
It updates the transaction dry run endpoint to accept a body with the transaction string, the sender address and the block number. it returns if the dry run was successful or if it errored and for which block hash
> feat: update dry run endpoint to use new runtime api call

- .github/dependabot.yml
- package.json
- yarn.lock
- Enables the Dependabot to update the packages that match the `@polkadot/*` pattern (same as in [ata](https://github.com/paritytech/asset-transfer-api/pull/457/files))
- Update again the pattern for the Dependabot PR title (same as in [ata](https://github.com/paritytech/asset-transfer-api/pull/464/files))
- Declare explicit pjs dependencies (same as in [ata](https://github.com/paritytech/asset-transfer-api/pull/458/files))
- We could declare explicitly more pjs deps in Sidecar. Not sure if it is needed.
> fix: dependabot yaml & explicit pjs deps declaration

- src/services/test-helpers/mock/mockAssetHubWestendApi.ts
- src/services/test-helpers/mock/mockDryRunError.ts
- src/services/transaction/TransactionDryRunService.spec.ts
- src/services/transaction/TransactionDryRunService.ts
- src/test-helpers/registries/assetHubWestendRegistry.ts
- src/types/responses/TransactionDryRun.ts
Closes https://github.com/paritytech/substrate-api-sidecar/issues/1532
Connected to Westend Asset Hub, when requesting: 
```
curl -X 'POST' \
'http://127.0.0.1:8080/transaction/dry-run' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '{
"senderAddress": "5F9aniqTwLsRn5ybqSeB2srKfaRXCLeNDSPPHQxPeuGw5Y8a",
"tx": "0x0a0000fe06fc3db07fb1a4ce89a76eaed1e54519b5940d2652b8d6794ad4ddfcdcb16c0f00d0eca2b99401"
}'
```
Before the change we would get the response : 
```
{"at":{"hash":"","height":"0"},"result":{"resultType":"DispatchError","result":{"postInfo":{"actualWeight":null,"paysFee":"Yes"},"error":{"token":"FundsUnavailable"}}}}
{"code":400,"error":"Unable to dry-run transaction","transaction":"0x0a0000fe06fc3db07fb1a4ce89a76eaed1e54519b5940d2652b8d6794ad4ddfcdcb16c0f00 …
```
> fix: return DispatchError in dry-run endpoint

- src/services/blocks/BlocksService.spec.ts
- src/services/blocks/BlocksService.ts
Closes https://github.com/paritytech/substrate-api-sidecar/issues/1538 
In the `blocks` endpoint, we return a list of extrinsics included in the queried block and under each extrinsic their related event. However, during `multiBlockMigrations` we encounter cases where events reference extrinsic indexes that do not exist. 
In the code, this situation is represented by having an event with : 
- phase set as `ApplyExtrinsic` [here](https://github.com/paritytech/substrate-api-sidecar/blob/cef2d10ead615b81c11a493310c84411fd45738f/src/services/blocks/BlocksService.ts#L589) (which means we expect an extrinsic associated with this event)
- then we retrieve the extrinsic index [here](https://github.com/paritytech/substrate-api-sidecar/blob/cef2d10ead615b81c11a493310c84411fd45738f/src/services/block …
> fix: ignore extrinsicIndex in multiBlockMigrations event

- .github/dependabot.yml
After reviewing this Dependabot PR https://github.com/paritytech/substrate-api-sidecar/pull/1534, I noticed that Dependabot does not update the `package.json` file. This is the expected behaviour since polkadot deps are using the caret `^` in [package.json](https://github.com/paritytech/substrate-api-sidecar/blob/master/package.json#L53L59) and Dependabot does not need to update it (default Dependabot versioning is [auto](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy)).
- `package.json` has a dependency in some version `"example-dep": "^14.1.1"`
- Dependabot will bump the version to the latest one (either patch or minor), e.g. `14.x.x` version so `14.2.2` or `14.1.3` 
- It will not …
> chore: update Dependabot versioning strategy

- README.md
- RELEASE.md
- benchmarks/README.md
- docs/README.md
- guides/CONTRIBUTING.md
Updated the docs to reflect the recent changes in Sidecar documentation & benchmarks.
This is a result from the changes in Sidecar workflows done by the CI Team. Related PRs: 
- https://github.com/paritytech/substrate-api-sidecar/pull/1531
- https://github.com/paritytech/substrate-api-sidecar/pull/1552
- When you update the documentation in a PR, it is no longer needed to build the docs (with `yarn build:docs`). You only need to update and commit the src/[openapi-v1.yaml](https://github.com/paritytech/substrate-api-sidecar/blob/master/docs/src/openapi-v1.yaml) file. The docs will be built & published automatically in `gh-pages` as soon as the PR is merged in `master` branch.
- Benchmarks are now published in Github pages as well under the URL …
> docs: update docs & benchmarks related docs

- package.json
- yarn.lock
Updated pjs deps from [v15.3.1](https://github.com/polkadot-js/api/releases/tag/v15.3.1) to [v15.5.1](https://github.com/polkadot-js/api/releases/tag/v15.5.1) : 
- `@polkadot/api`
- `@polkadot/api-augment`
- `@polkadot/api-contract`
- `@polkadot/types`
- `@polkadot/types-codec`
> chore(deps): update polkadot-js deps to v15.5.1

- .github/workflows/benchmark.yml
Closes https://github.com/paritytech/substrate-api-sidecar/issues/1584
This PR adds a step in the `Benchmark` workflow that makes `generate_benchmark_result` script executable. This change aims to resolve the `Permission denied` error described in the linked issue.
> fix: benchmark-publish job (github action)

- CHANGELOG.md
- RELEASE.md
- docs/src/openapi-v1.yaml
- package.json
This release includes the staking related [PR](https://github.com/paritytech/substrate-api-sidecar/pull/1445) which breaks the `staking-info` endpoint. It is mentioned separately in the "Breaking Changes" section.
> chore(release): 20.0.0

- docs/src/openapi-v1.yaml
- src/controllers/accounts/AccountsStakingInfoController.ts
- src/services/accounts/AccountsStakingInfoService.spec.ts
- src/services/accounts/AccountsStakingInfoService.ts
- src/services/test-helpers/responses/accounts/stakingInfo22939322ClaimedFalse.json
This PR adds the `includeClaimedRewards` query param in the endpoint `/accounts/{accountId}/staking-info`. When set to `false`:
- the field `claimedRewards` will be omitted from the response and
- all internal calculations for claimed rewards in `AccountsStakingInfoService` will be skipped, potentially speeding up the response time. 
Defaults to `true` so it does not break the current functionality of the endpoint.
An exchange reported significantly long response times for the endpoint `/accounts/{accountId}/staking-info` after the release of [v20.0.0](https://github.com/paritytech/substrate-api-sidecar/releases/tag/v20.0.0). This is most likely due to the breaking changes introduced to this endpoint (calculation of `claimedRewards` changed). To address this, a new flag/query parameter …
> feat: add `includeClaimedRewards` query param in staking-info

- docs/src/openapi-v1.yaml
- src/chains-config/assetHubKusamaControllers.ts
- src/chains-config/assetHubPolkadotControllers.ts
- src/chains-config/assetHubWestendControllers.ts
- src/chains-config/kusamaControllers.ts
- src/chains-config/polkadotControllers.ts
- src/chains-config/westendControllers.ts
- src/controllers/accounts/AccountsCompareController.ts
- src/controllers/accounts/index.ts
- src/controllers/index.ts
- src/middleware/validate/validateAddressMiddleware.ts
- src/services/accounts/AccountsCompareService.spec.ts
- src/services/accounts/AccountsCompareService.ts
- src/services/accounts/index.ts
- src/types/requests.ts
- src/types/responses/AccountCompare.ts
Closes https://github.com/paritytech/substrate-api-sidecar/issues/1591
Adds a new endpoint, `accounts/compare`, that compares up to 30 `SS58` addresses and determines if they are equal which means that they share the same public key. Returns a boolean result along with detailed information for each address queried.
- The request should be follow one of these formats : 
- by repeating the `addresses` key: `?addresses=...&addresses=...` or
- by using the array style key: `?addresses[]=...&addresses[]=...` or
- by using comma-separated values: `?addresses=...,...`.
- The limit of 30 addresses was set to keep the character count of the request at a reasonable size/not too big.
- The additional function `validateAddressQueryParamMiddleware` was added to check that the addresses as query …
> feat: add accounts/compare endpoint

- src/chains-config/index.ts
Updating the specName for `Asset-Hub-Next` so that it loads the controllers defined in [assetHubNextWestendControllers.ts](https://github.com/paritytech/substrate-api-sidecar/blob/2c926c786536bfee73b1875909c13d0750284090/src/chains-config/assetHubNextWestendControllers.ts#L23) when connected to `Westend Asset Hub Next` rather than the default ones. 
This is no blocker since Sidecar is still working with the `defaultControllers` which include the essential Staking and Balance endpoints.
Tested with Westend Asset Hub Next endpoint and it is working as expected.
> fix: asset-hub-next specName

- src/services/accounts/AccountsStakingPayoutsService.ts
Closes https://github.com/paritytech/substrate-api-sidecar/issues/1610
Relates to : https://github.com/paritytech/substrate-api-sidecar/issues/1361
I measured the execution time of the nested loops (old code) by doing the following:
1. I added : 
```
const start = performance.now();
```
right before the `stakers.forEach...` statement so in line [579](https://github.com/paritytech/substrate-api-sidecar/blob/master/src/services/accounts/AccountsStakingPayoutsService.ts#L579).
2. and this code:
```
const end = performance.now();
console.log(`Execution time in mapStakers: ${end - start} ms`);
```
right after the loop ended so right after line [609](https://github.com/paritytech/substrate-api-sidecar/blob/eae70c15b5a48db3a3ecb7fc1c2b24ff85145534/src/services/accounts/AccountsStakingPayoutsServi …
> perf: optimization of mapStakers function

- src/controllers/controllerInjection.spec.ts
This PR aims to minimize the frequency in which the tests fail (with `yarn test`) in PRs, especially the ones opened from the Dependabot.
In the last PRs, the tests in [controllerInjection.spec.ts](https://github.com/paritytech/substrate-api-sidecar/compare/domi-injection-timeout?expand=1#diff-1378505656c30b1e4f18b5b171c61cfa1937fe1f2025c8cc38ccde9ca943f6d6) were failing either with error:
```
controllerInjection › should return the correct response for bifrost_polkadot
thrown: "Exceeded timeout of 10000 ms for a test.
```
Example [here](https://github.com/paritytech/substrate-api-sidecar/actions/runs/14360119412/job/40260173475)
or with error
```
2025-04-09 13:51:01          API-WS: disconnected from wss://calamari.systems: 1006:: Abnormal Closure
```
Example …
> fix: small updates in injection tests

- src/services/transaction/TransactionDryRunService.spec.ts
- src/services/transaction/TransactionDryRunService.ts
rel: https://github.com/paritytech/substrate-api-sidecar/pull/1649
This ensures that when no xcmVersion is present in the body it will default to the safeXcmVersion provided by the xcmPallet.
> fix: retreive safeXcmVersion when xcmVersion is not in the body

- docs/src/openapi-v1.yaml
- src/chains-config/index.ts
- src/controllers/AbstractController.ts
- src/controllers/pallets/PalletsStakingProgressController.ts
- src/middleware/validate/index.ts
- src/middleware/validate/validateRcAtMiddleware.ts
- src/types/responses/PalletStakingProgress.ts
Added comprehensive `rcAt` parameter support with the following components:
- **`getAhAtFromRcAt(at, maxDepth)`**: Resolves relay chain block numbers to Asset Hub block hashes by searching for `paraInclusion.CandidateIncluded` events for paraId 1000
- **`findAhBlockInRcBlock()`**: Recursively searches parent blocks when Asset Hub isn't included in the specified relay chain block
- **`getHashFromRcAt(rcAt)`**: High-level method that wraps the resolution logic and returns both AH hash and RC block number
- **Block format validation**: Ensures `rcAt` is a valid block number or 32-byte hex hash
- **Mutual exclusivity**: Prevents using both `at` and `rcAt` parameters simultaneously
- **Asset Hub requirement**: Validates that the current API is connected to Asset Hub
- **Relay chain …
> feat: Add `rcAt` query parameter support for Asset Hub Migration

- docs/src/openapi-v1.yaml
- src/controllers/pallets/PalletsAssetConversionController.ts
- src/controllers/pallets/PalletsAssetsController.ts
- src/controllers/pallets/PalletsConstsController.ts
- src/controllers/pallets/PalletsDispatchablesController.ts
- src/controllers/pallets/PalletsErrorsController.ts
- src/controllers/pallets/PalletsEventsController.ts
- src/controllers/pallets/PalletsForeignAssetsController.ts
- src/controllers/pallets/PalletsNominationPoolsController.ts
- src/controllers/pallets/PalletsOnGoingReferendaController.ts
- src/controllers/pallets/PalletsPoolAssetsController.ts
- src/controllers/pallets/PalletsStakingValidatorsController.ts
- src/controllers/pallets/PalletsStorageController.ts
Summary
- Adds rcAt parameter support to multiple pallets endpoints for Asset Hub relay chain integration
- Enhances responses with relay chain context when rcAt parameter is used
Endpoints with rcAt support added:
- /pallets/nomination-pools/info
- /pallets/nomination-pools/{poolId}
- /pallets/on-going-referenda
- /pallets/{palletId}/consts
- /pallets/{palletId}/consts/{constItemId}
- /pallets/{palletId}/dispatchables
- /pallets/{palletId}/dispatchables/{dispatchableItemId}
- /pallets/{palletId}/errors
- /pallets/{palletId}/errors/{errorItemId}
- /pallets/{palletId}/events
- /pallets/{palletId}/events/{eventItemId}
- /pallets/{palletId}/storage
- /pallets/{palletId}/storage/{storageItemId}
- /pallets/pool-assets/{assetId}/asset-info
- /pallets/staking/validators
> feat: Support `rcAt` for `/pallets/*` endpoints

- docs/src/openapi-v1.yaml
- src/services/accounts/AccountsBalanceInfoService.spec.ts
- src/services/accounts/AccountsBalanceInfoService.ts
- src/services/test-helpers/responses/accounts/balanceInfo789629.json
- src/services/test-helpers/responses/accounts/balanceInfoFeeFrozen.json
- src/types/responses/AccountBalanceInfo.ts
This PR adds the `transferable` field to balance-info endpoints and provides documentation explaining its calculation.
- Added `transferable` field to the `IAccountBalanceInfo` interface with detailed JSDoc documentation
- Updated OpenAPI schema to include the `transferable` field for both balance-info endpoints:
- `/accounts/{accountId}/balance-info`
- `/rc/accounts/{address}/balance-info`
The transferable balance uses the formula: `free - max(maybeEd, frozen - reserve)`
Where:
- `maybeEd` is the existential deposit if there are frozen funds or reserves, otherwise zero
- This represents the actual spendable balance after accounting for locks, reserves, and the existential deposit
NOTE: The polkadot-js implementation I am using here is a UI-friendly calculation that considers:
- When the …
> feat: Add transferable field to `/accounts/{accountId}/balance-info`

- src/chains-config/index.ts
- src/services/accounts/AccountsStakingPayoutsService.ts
This ensures that staking payouts is dynamic for dealing with post migration querying with eras. Since we require the start and end block of both the relay chain and asset hub when query a depth of 84 from a certain block on assetHub it's required we need this information in storage, before we can get it hardcoded in the codebase.
We also added `asset-hub-paseo` to the config.
`/accounts/{accountId}/staking-payouts`
> fix: Add support for migrationStartBlock and migrationEndBlock storage in staking

- docs/src/openapi-v1.yaml
- src/chains-config/assetHubKusamaControllers.ts
- src/chains-config/assetHubNextWestendControllers.ts
- src/chains-config/assetHubPolkadotControllers.ts
- src/chains-config/assetHubWestendControllers.ts
- src/chains-config/kusamaControllers.ts
- src/chains-config/polkadotControllers.ts
- src/chains-config/westendControllers.ts
- src/controllers/ahm/AhmInfoController.ts
- src/controllers/ahm/index.ts
- src/controllers/index.ts
- src/services/accounts/AccountsStakingPayoutsService.ts
- src/services/ahm/AhmInfoService.spec.ts
- src/services/ahm/AhmInfoService.ts
- src/services/ahm/index.ts
- src/services/consts.ts
Adds a new REST endpoint `/ahm-info` that provides Asset Hub Migration (AHM) boundary information including migration start/end blocks for both relay chain and Asset Hub.
- **Controller**: `AhmInfoController` with GET `/ahm-info` endpoint
- **Service**: `AhmInfoService` with smart dual-mode detection logic
- **Types**: `IAhmInfo` interface for structured migration data
- **Constants**: Migration boundaries for Westend and Paseo networks
- **Documentation**: Complete OpenAPI spec with new `ahm` tag and schema
```json
{
"relay": {
"startBlock": 26041702,
"endBlock": 26071771
},
"assetHub": {
"startBlock": 11716733,
"endBlock": 11736597
}
}
Usage
GET /ahm-info - Returns migration boundaries for current chain context
> feat: Add /ahm-info endpoint

- src/services/pallets/PalletsStakingProgressService.ts
`isApiAssetHub` may be undefined when the multi chain input doesn't set assethubs specName. It is not required to have the specName as part of the multi chain input, but also the logic was redundant internally, and can be removed.
> fix: remove redundant isApiAssetHub specName check

- docs-v2/openapi-v1.yaml
- docs/src/openapi-v1.yaml
The following schema refs were broken when I imported the schema into https://editor.swagger.io/
```
$ref: '#/components/schemas/RuntimeMetadata'
$ref: '#/components/schemas/PalletsConstants'
$ref: '#/components/schemas/PalletsConstantsItem'
$ref: '#/components/schemas/PalletsDispatchables'
$ref: '#/components/schemas/PalletsDispatchablesItem'
$ref: '#/components/schemas/PalletsErrors'
$ref: '#/components/schemas/PalletsErrorsItem'
$ref: '#/components/schemas/PalletsEvents'
$ref: '#/components/schemas/PalletsEventsItem'
$ref: '#/components/schemas/PalletsStorage'
$ref: '#/components/schemas/PalletsStorageItem'
```
`RuntimeMetadata` didn't exist and the rest should have been `Pallet` instead of `Pallets`. This PR fixes those.
I also updated the `tags` for `rc` endpoints as some appeared in …
> fix: update broken schema refs + more granular rc tags
